Repository fiuba-laboral-v2/front-end, pull requests merged in 2020-09, with the labels that each got.

#242 Fix/270 redirect to login
  src/models/hooks/queries/useCurrentUser.ts
Labels: fix

#241 Reimplement fetchMore
  src/cache/typePolicies/queries/paginatedQuery.ts
  src/components/Button/index.tsx
  src/components/Card/component.tsx
  src/components/ErrorPage/index.tsx
  src/components/FormConfirmDialog/index.tsx
  src/components/FormFooter/index.tsx
  src/components/List/component.tsx
  src/components/List/container.tsx
  src/components/List/interface.ts
  src/components/List/styles.module.scss
  src/interfaces/Pagination/index.ts
  src/models/errorHandlers/handleGenericError.ts
  src/models/hooks/mutations/useUpdateAdminTaskStatusMutation.ts
  src/models/hooks/queries/interface.ts
  src/models/hooks/queries/useAdminTasks.ts
  src/models/hooks/queries/useMyJobApplications.ts
  src/models/hooks/queries/useMyOffers.ts
  src/models/hooks/queries/useOffers.ts
  src/models/hooks/snackbar/useShowError.tsx
  src/models/hooks/useQuery.ts
  src/pages/Admin/Home/Dashboard/Menu/container.tsx
  src/pages/Admin/Home/Dashboard/Menu/interfaces.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/ApproveButton/index.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/PendingButton/index.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/RejectButton/index.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/StatusButton/component.tsx
  src/pages/Admin/Home/Dashboard/TaskList/ListBody/component.tsx
  src/pages/Admin/Home/Dashboard/TaskList/ListBody/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskList/container.tsx
  src/pages/Admin/Home/Dashboard/TaskList/interface.ts
  src/pages/Admin/Home/Dashboard/component.tsx
  src/pages/Admin/Home/Dashboard/container.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
  src/pages/Applicant/Home/Feed/component.tsx
  src/pages/Applicant/Home/Feed/container.tsx
  src/pages/Applicant/Home/Feed/styles.module.scss
  src/pages/Applicant/OfferDetail/component.tsx
  src/pages/Applicant/Profile/component.tsx
  src/pages/Company/MyJobApplications/JobApplication/component.tsx
  src/pages/Company/MyJobApplications/component.tsx
  src/pages/Company/MyJobApplications/container.tsx
  src/pages/Company/MyJobApplications/styles.module.scss
  src/pages/Company/MyOffers/container.tsx
  src/pages/Company/OfferDetail/container.tsx
  src/pages/Company/Profile/component.tsx
  src/pages/Company/SignUp/component.tsx
  src/pages/Public/LogIn/LogInForm/component.tsx
Labels: fix

#244 Feature/280 status label
  package.json
  src/components/ApplicantDetail/component.tsx
  src/components/ApprovedLabel/index.tsx
  src/components/CompanyDetail/index.tsx
  src/components/Label/index.tsx
  src/components/Label/styles.module.scss
  src/components/OfferDetail/component.tsx
  src/components/OfferDetail/styles.module.scss
  src/components/PendingLabel/index.tsx
  src/components/RejectedLabel/index.tsx
  src/components/SeparatedStatusLabel/component.tsx
  src/components/SeparatedStatusLabel/container.tsx
  src/components/SeparatedStatusLabel/index.tsx
  src/components/SeparatedStatusLabel/interfaces.ts
  src/components/SeparatedStatusLabel/styles.module.scss
  src/components/SharedStatusLabel/component.tsx
  src/components/SharedStatusLabel/container.tsx
  src/components/SharedStatusLabel/index.ts
  src/components/SharedStatusLabel/interfaces.ts
  src/components/StatusLabel/index.tsx
  src/components/StatusTitle/index.tsx
  src/models/hooks/index.ts
  src/models/hooks/useStatusText.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/JobApplication/DetailContent/interfaces.ts
  src/pages/Admin/Home/Dashboard/TaskList/AdminTask/component.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
  src/pages/Applicant/SignUp/component.tsx
  src/pages/Company/EditableProfile/component.tsx
  src/pages/Company/OfferDetail/container.tsx
  src/pages/Company/SignUp/component.tsx
  src/pages/Public/LogIn/LogInForm/component.tsx
  src/styles/_variables.scss
  tsconfig.json
  yarn.lock
Labels: feature

#249 Remove unused parameters
  src/components/List/component.tsx
  src/components/List/container.tsx
  src/components/List/interface.ts
  src/components/SearchSelector/MultipleSearchSelector/index.tsx
  src/components/SearchSelector/SearchSelector/index.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
  src/pages/Applicant/Home/Feed/component.tsx
  src/pages/Public/LogIn/LogInForm/container.tsx
  tsconfig.json
Labels: feature

#247 show status according to the targetApplicantType
  src/components/Label/index.tsx
  src/components/Label/styles.module.scss
  src/components/OfferDetail/component.tsx
  src/components/SeparatedStatusLabel/component.tsx
  src/components/SeparatedStatusLabel/container.tsx
  src/components/SeparatedStatusLabel/interfaces.ts
  src/components/SharedStatusLabel/component.tsx
  src/components/SharedStatusLabel/interfaces.ts
  src/components/StatusTitle/index.tsx
  src/pages/Admin/Home/Dashboard/TaskList/AdminTask/component.tsx
  tsconfig.json
Labels: feature

#250 Refactor/move feed to components
  src/components/Feed/Offer/Info/JobSpecs/SpecItem/index.tsx
  src/components/Feed/Offer/Info/JobSpecs/SpecItem/styles.module.scss
  src/components/Feed/Offer/Info/JobSpecs/component.tsx
  src/components/Feed/Offer/Info/JobSpecs/container.tsx
  src/components/Feed/Offer/Info/JobSpecs/index.tsx
  src/components/Feed/Offer/Info/JobSpecs/interfaces.ts
  src/components/Feed/Offer/Info/component.tsx
  src/components/Feed/Offer/Info/index.tsx
  src/components/Feed/Offer/Info/styles.module.scss
  src/components/Feed/Offer/component.tsx
  src/components/Feed/Offer/index.tsx
  src/components/Feed/Offer/styles.module.scss
  src/components/Feed/index.tsx
  src/components/Feed/styles.module.scss
  src/pages/Applicant/Home/Feed/container.tsx
  src/pages/Company/MyOffers/container.tsx
Labels: refactor

#251 Feature/279 feed status label
  src/components/ApplicantDetail/styles.module.scss
  src/components/Feed/Offer/Info/StatusLabels/index.tsx
  src/components/Feed/Offer/Info/StatusLabels/styles.module.scss
  src/components/Feed/Offer/Info/component.tsx
  src/components/Feed/Offer/Info/styles.module.scss
  src/components/Feed/Offer/component.tsx
  src/components/Feed/index.tsx
  src/components/Label/index.tsx
  src/components/Label/styles.module.scss
  src/components/OfferDetail/StatusLabels/index.tsx
  src/components/OfferDetail/StatusLabels/styles.module.scss
  src/components/OfferDetail/component.tsx
  src/components/OfferDetail/styles.module.scss
  src/components/SeparatedStatusLabel/component.tsx
  src/components/SeparatedStatusLabel/container.tsx
  src/components/SeparatedStatusLabel/index.tsx
  src/components/SeparatedStatusLabel/interfaces.ts
  src/components/StatusLabel/ApprovedLabel/index.tsx
  src/components/StatusLabel/PendingLabel/index.tsx
  src/components/StatusLabel/RejectedLabel/index.tsx
  src/components/StatusLabel/index.tsx
  src/components/StatusTitle/index.tsx
  src/components/StatusTitle/styles.module.scss
  src/graphql/queries/getMyOffers.graphql
  src/models/hooks/index.ts
  src/models/hooks/useSeparatedStatusTranslations.ts
  src/pages/Admin/Home/Dashboard/Icons/ApplicantIcon/index.tsx
  src/pages/Admin/Home/Dashboard/Icons/CompanyIcon/index.tsx
  src/pages/Admin/Home/Dashboard/Icons/JobApplicationIcon/index.tsx
  src/pages/Admin/Home/Dashboard/Icons/OfferIcon/index.tsx
  src/pages/Admin/Home/Dashboard/TaskList/AdminTask/StatusIcon/index.tsx
  src/pages/Admin/Home/Dashboard/TaskList/AdminTask/StatusIcon/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskList/AdminTask/component.tsx
  src/pages/Admin/Home/Dashboard/TaskList/AdminTask/styles.module.scss
  src/pages/Applicant/Home/Feed/container.tsx
  src/pages/Company/MyOffers/container.tsx
Labels: feature

#254 Feature/282 get approved offers query
  src/components/Label/index.tsx
  src/components/SeparatedStatusLabel/index.tsx
  src/components/TargetApplicantTypeSelector/component.tsx
  src/components/TargetApplicantTypeSelector/interfaces.ts
  src/graphql/mutations/createOffer.graphql
  src/graphql/mutations/editOffer.graphql
  src/graphql/queries/getApprovedOffers.graphql
  src/graphql/queries/index.ts
  src/interfaces/Applicant/index.ts
  src/interfaces/Offer/index.tsx
  src/models/hooks/mutations/useCreateOffer.ts
  src/models/hooks/queries/index.ts
  src/models/hooks/queries/useApprovedOffers.ts
  src/models/hooks/queries/useOffers.ts
  src/models/hooks/queries/usePaginatedOffers.ts
  src/models/hooks/useSeparatedStatusTranslations.ts
  src/pages/Applicant/Home/Feed/container.tsx
Labels: feature

#255 Feature/tpp 306
  src/components/ApplicantDetail/component.tsx
  src/components/Card/styles.module.scss
  src/components/CareersDetail/GraduateCareerDetail/index.tsx
  src/components/CareersDetail/StudentCareerDetail/index.tsx
  src/components/CareersDetail/component.tsx
  src/components/CareersDetail/container.tsx
  src/components/CareersSection/CareersDetail/component.tsx
  src/components/CareersSection/CareersDetail/container.tsx
  src/components/CareersSection/CareersDetail/index.tsx
  src/components/CareersSection/CareersDetail/interfaces.ts
  src/components/CareersSection/GraduateCareerDetail/index.tsx
  src/components/CareersSection/GraduateCareerDetail/styles.module.scss
  src/components/CareersSection/StudentCareerDetail/index.tsx
  src/components/CareersSection/StudentCareerDetail/styles.module.scss
  src/components/CareersSection/component.tsx
  src/components/CareersSection/container.tsx
  src/components/CareersSection/index.tsx
  src/components/CareersSection/interface.tsx
  src/components/CareersSection/styles.module.scss
  src/components/Header/styles.module.scss
  src/graphql/queries/getApplicants.graphql
  src/interfaces/Applicant/index.ts
  src/interfaces/User/index.ts
  src/models/RoutesBuilder.ts
  src/models/hooks/queries/index.ts
  src/models/hooks/queries/useApplicants.ts
  src/pages/Admin/Applicants/ApplicantList/Columns/index.tsx
  src/pages/Admin/Applicants/ApplicantList/ListContainer/index.tsx
  src/pages/Admin/Applicants/ApplicantList/ListContainer/styles.module.scss
  src/pages/Admin/Applicants/ApplicantList/ListContent/Item/index.tsx
  src/pages/Admin/Applicants/ApplicantList/ListContent/Item/styles.module.scss
  src/pages/Admin/Applicants/ApplicantList/ListContent/Row/index.tsx
  src/pages/Admin/Applicants/ApplicantList/ListContent/Row/styles.module.scss
  src/pages/Admin/Applicants/ApplicantList/ListContent/component.tsx
  src/pages/Admin/Applicants/ApplicantList/ListContent/container.tsx
  src/pages/Admin/Applicants/ApplicantList/ListContent/index.ts
  src/pages/Admin/Applicants/ApplicantList/ListHeader/HeaderContainer/index.tsx
  src/pages/Admin/Applicants/ApplicantList/ListHeader/HeaderContainer/styles.module.scss
  src/pages/Admin/Applicants/ApplicantList/ListHeader/Item/index.tsx
  src/pages/Admin/Applicants/ApplicantList/ListHeader/Item/styles.module.scss
  src/pages/Admin/Applicants/ApplicantList/ListHeader/component.tsx
  src/pages/Admin/Applicants/ApplicantList/ListHeader/container.tsx
  src/pages/Admin/Applicants/ApplicantList/ListHeader/index.ts
  src/pages/Admin/Applicants/ApplicantList/component.tsx
  src/pages/Admin/Applicants/ApplicantList/constants.ts
  src/pages/Admin/Applicants/ApplicantList/index.ts
  src/pages/Admin/Applicants/MainContainer/index.tsx
  src/pages/Admin/Applicants/MainContainer/styles.module.scss
  src/pages/Admin/Applicants/MainTitle/container.tsx
  src/pages/Admin/Applicants/MainTitle/index.ts
  src/pages/Admin/Applicants/component.tsx
  src/pages/Admin/Applicants/index.ts
  src/pages/Admin/routes.tsx
  src/styles/_variables.scss
  src/styles/mixins/_lists.scss
Labels: feature

#260 add admin links in navbar
  src/components/NavBar/interface.ts
  src/models/NavBarLinks/AdminNavBarLinks.ts
  src/models/NavBarLinks/NavBarLinks.ts
  src/test/models/NavBarLinks/NavBarLinks.test.ts
Labels: feature

#261 Refactor/323 generic paginated query
  src/graphql/queries/getMyLatestJobApplications.graphql
  src/models/hooks/queries/index.ts
  src/models/hooks/queries/useAdminTasks.ts
  src/models/hooks/queries/useApprovedOffers.ts
  src/models/hooks/queries/useMyJobApplications.ts
  src/models/hooks/queries/useOffers.ts
  src/models/hooks/queries/usePaginatedOffers.ts
  src/models/hooks/queries/usePaginatedQuery.ts
  src/pages/Company/MyJobApplications/component.tsx
Labels: refactor

#267 Feature/320 get offer
  src/graphql/queries/getOfferVisibleByCurrentApplicant.graphql
  src/graphql/queries/index.ts
  src/models/handleError.ts
  src/models/hooks/queries/useOfferByUuid.ts
  src/pages/Applicant/OfferDetail/container.tsx
Labels: feature

#268 refactor of list pages
  src/pages/Admin/Applicants/ApplicantList/ListContent/Row/index.tsx
  src/pages/Admin/Applicants/ApplicantList/ListContent/component.tsx
  src/pages/Admin/Applicants/ApplicantList/ListContent/container.tsx
  src/pages/Admin/Applicants/ApplicantList/ListContent/index.ts
  src/pages/Admin/Applicants/ApplicantList/ListHeader/HeaderContainer/index.tsx
  src/pages/Admin/Applicants/ApplicantList/component.tsx
  src/pages/Admin/Applicants/ApplicantList/index.ts
  src/pages/Admin/Applicants/Columns/index.tsx
  src/pages/Admin/Applicants/ListContentItem/index.tsx
  src/pages/Admin/Applicants/ListContentItem/styles.module.scss
  src/pages/Admin/Applicants/ListHeader/Item/index.tsx
  src/pages/Admin/Applicants/ListHeader/Item/styles.module.scss
  src/pages/Admin/Applicants/ListHeader/component.tsx
  src/pages/Admin/Applicants/ListHeader/container.tsx
  src/pages/Admin/Applicants/ListHeader/index.ts
  src/pages/Admin/Applicants/component.tsx
  src/pages/Admin/Applicants/constants.ts
  src/pages/Admin/Applicants/container.tsx
  src/pages/Admin/Applicants/index.ts
  src/pages/Admin/Applicants/styles.module.scss
  src/pages/Admin/components/ListPageContainer/List/ListContainer/index.tsx
  src/pages/Admin/components/ListPageContainer/List/ListContainer/styles.module.scss
  src/pages/Admin/components/ListPageContainer/List/ListContent/Row/index.tsx
  src/pages/Admin/components/ListPageContainer/List/ListContent/Row/styles.module.scss
  src/pages/Admin/components/ListPageContainer/List/ListContent/index.tsx
  src/pages/Admin/components/ListPageContainer/List/ListHeader/index.tsx
  src/pages/Admin/components/ListPageContainer/List/ListHeader/styles.module.scss
  src/pages/Admin/components/ListPageContainer/List/index.tsx
  src/pages/Admin/components/ListPageContainer/MainContainer/index.tsx
  src/pages/Admin/components/ListPageContainer/MainContainer/styles.module.scss
  src/pages/Admin/components/ListPageContainer/MainTitle/container.tsx
  src/pages/Admin/components/ListPageContainer/MainTitle/index.tsx
  src/pages/Admin/components/ListPageContainer/index.tsx
  src/pages/Admin/components/ListPageContainer/interfaces.ts
Labels: refactor

#269 Add Empresas link in navbar
  src/models/NavBarLinks/AdminNavBarLinks.ts
  src/models/RoutesBuilder.ts
  src/pages/Admin/Companies/container.tsx
  src/pages/Admin/Companies/index.ts
  src/pages/Admin/routes.tsx
  src/test/models/NavBarLinks/NavBarLinks.test.ts
Labels: feature

#271 Disable status button until request is resumed
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/ApproveButton/index.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/RejectButton/index.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/StatusButton/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/StatusButton/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/StatusButton/interfaces.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/index.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Applicant/ApplicantDetailInfo/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/DetailInfo/index.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/JobApplication/DetailInfo/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Offer/OfferDeatilInfo/component.tsx
Labels: fix

#270 agregado de businessName en el registro de company (razon social)
  src/components/CompanyFields/component.tsx
  src/components/CompanyFields/interface.ts
  src/models/hooks/mutations/useCreateCompany.ts
  src/pages/Company/SignUp/component.tsx
Labels: feature

#275 Fix edit company by adding bussinesName
  src/components/CompanyFields/component.tsx
  src/graphql/queries/getMyCompanyProfile.graphql
Labels: fix

#276 Feature/319 get offer by UUID permissions
  src/graphql/queries/getOfferByUuid.graphql
  src/graphql/queries/getOfferForApplicant.graphql
  src/graphql/queries/index.ts
  src/models/hooks/queries/useOfferByUuid.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/Offer/OfferDetailContent/component.tsx
  src/pages/Applicant/OfferDetail/container.tsx
Labels: feature

#277 paginado en applicant list
  src/cache/typePolicies/queries/index.ts
  src/components/List/container.tsx
  src/components/List/index.tsx
  src/components/List/interface.ts
  src/components/List/styles.module.scss
  src/components/PaginationButton/component.tsx
  src/components/PaginationButton/container.tsx
  src/components/PaginationButton/index.tsx
  src/components/PaginationButton/interface.ts
  src/components/PaginationButton/styles.module.scss
  src/graphql/queries/getApplicants.graphql
  src/models/hooks/queries/useApplicants.ts
  src/models/hooks/queries/useMyJobApplications.ts
  src/models/hooks/queries/useOffers.ts
  src/models/hooks/queries/usePaginatedQuery.ts
  src/pages/Admin/Applicants/container.tsx
  src/pages/Admin/Companies/container.tsx
  src/pages/Admin/components/ListPageContainer/List/ListContent/index.tsx
  src/pages/Admin/components/ListPageContainer/List/ListContent/interface.ts
  src/pages/Admin/components/ListPageContainer/List/ListContent/styles.module.scss
  src/pages/Admin/components/ListPageContainer/List/index.tsx
  src/pages/Admin/components/ListPageContainer/index.tsx
Labels: feature

#282 Use bootstrap's default font
  src/styles/base.scss
Labels: feature

#285 Fix/347 unmounted component
  src/components/NavBar/container.tsx
  src/graphql/mutations/createOffer.graphql
  src/graphql/mutations/editOffer.graphql
  src/models/hooks/mutations/useCreateCompany.ts
  src/models/hooks/mutations/useCreateOffer.ts
  src/models/hooks/mutations/useEditOffer.ts
  src/models/hooks/mutations/useLogin.ts
  src/models/hooks/mutations/useLogout.ts
  src/models/hooks/mutations/useSaveApplicant.ts
  src/models/hooks/mutations/useUpdateAdminTaskStatus.ts
  src/models/hooks/mutations/useUpdateAdminTaskStatusMutation.ts
  src/models/hooks/mutations/useUpdateCurrentApplicant.ts
  src/models/hooks/mutations/useUpdateCurrentCompany.ts
  src/models/hooks/useMutation.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/ApproveButton/index.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/RejectButton/index.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/StatusButton/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/StatusButton/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/StatusButton/interfaces.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/index.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Applicant/ApplicantDetailInfo/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Applicant/ApplicantDetailInfo/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/DetailInfo/index.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/JobApplication/DetailInfo/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/JobApplication/DetailInfo/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Offer/OfferDeatilInfo/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Offer/OfferDeatilInfo/container.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/OfferDetail/container.tsx
  src/pages/Applicant/SignUp/container.tsx
  src/pages/Company/CreateOffer/container.tsx
  src/pages/Company/EditOffer/container.tsx
  src/pages/Company/EditableProfile/container.tsx
  src/pages/Company/SignUp/container.tsx
  src/pages/Public/LogIn/LogInForm/container.tsx
Labels: fix

#286 Fix ICreateOffer interface
  src/components/EditOffer/index.tsx
  src/interfaces/Offer/index.tsx
  src/models/hooks/mutations/useCreateOffer.ts
  src/models/hooks/mutations/useEditOffer.ts
  src/pages/Company/EditOffer/container.tsx
Labels: fix
