Repository fiuba-laboral-v2/front-end, pull requests merged in 2020-03, with the labels that each got.

#25 Feature/88 adapt to new files distribution convention
  .gitignore
  src/pages/Applicant/Detail/ApplicantDetail/component.tsx
  src/pages/Applicant/Detail/ApplicantDetail/container.tsx
  src/pages/Applicant/Detail/ApplicantDetail/index.tsx
  src/pages/Applicant/Detail/ApplicantDetail/interface.tsx
  src/pages/Applicant/Detail/ApplicantDetail/styles.module.scss
  src/pages/Applicant/Detail/ApplicantTitle/container.tsx
  src/pages/Applicant/Detail/ApplicantTitle/index.tsx
  src/pages/Applicant/Detail/CapabilitiesDetail/component.tsx
  src/pages/Applicant/Detail/CapabilitiesDetail/index.tsx
  src/pages/Applicant/Detail/CapabilitiesDetail/interface.tsx
  src/pages/Applicant/Detail/CareersDetail/component.tsx
  src/pages/Applicant/Detail/CareersDetail/container.tsx
  src/pages/Applicant/Detail/CareersDetail/index.tsx
  src/pages/Applicant/Detail/CareersDetail/interface.tsx
  src/pages/Applicant/Detail/index.tsx
  src/pages/Applicant/Edit/ApplicantDetailEditable/component.tsx
  src/pages/Applicant/Edit/ApplicantDetailEditable/container.tsx
  src/pages/Applicant/Edit/ApplicantDetailEditable/index.tsx
  src/pages/Applicant/Edit/ApplicantDetailEditable/interface.tsx
  src/pages/Applicant/Edit/ApplicantDetailEditable/styles.module.scss
  src/pages/Applicant/Edit/ApplicantDetailEditableTitle/container.tsx
  src/pages/Applicant/Edit/ApplicantDetailEditableTitle/index.tsx
  src/pages/Applicant/Edit/EditableCapabilities/component.tsx
  src/pages/Applicant/Edit/EditableCapabilities/container.tsx
  src/pages/Applicant/Edit/EditableCapabilities/index.tsx
  src/pages/Applicant/Edit/EditableCapabilities/interface.tsx
  src/pages/Applicant/Edit/EditableCapabilities/styles.module.scss
  src/pages/Applicant/Edit/EditableCareers/component.tsx
  src/pages/Applicant/Edit/EditableCareers/container.tsx
  src/pages/Applicant/Edit/EditableCareers/index.tsx
  src/pages/Applicant/Edit/EditableCareers/interface.tsx
  src/pages/Applicant/Edit/EditableCareers/styles.module.scss
  src/pages/Applicant/Edit/index.tsx
  src/pages/Applicant/SignUp/component.tsx
  src/pages/Company/CompanyDetail/component.tsx
  src/pages/Company/CompanyDetail/container.tsx
  src/pages/Company/CompanyDetail/index.tsx
  src/pages/Company/CompanyDetail/interface.tsx
  src/pages/Company/CompanyDetail/styles.module.scss
  src/pages/Company/CompanyTitle/container.tsx
  src/pages/Company/CompanyTitle/index.tsx
  src/pages/Company/index.tsx
Labels: enhancement

#26 Feature/88 rename components to avoid redundancy
  src/pages/Applicant/Detail/ApplicantDetail/index.tsx
  src/pages/Applicant/Detail/ApplicantTitle/index.tsx
  src/pages/Applicant/Detail/index.tsx
  src/pages/Applicant/Edit/ApplicantDetailEditable/index.tsx
  src/pages/Applicant/Edit/ApplicantDetailEditableTitle/index.tsx
  src/pages/Applicant/Edit/index.tsx
  src/pages/Applicant/EditableProfile/EditableCapabilities/component.tsx
  src/pages/Applicant/EditableProfile/EditableCapabilities/container.tsx
  src/pages/Applicant/EditableProfile/EditableCapabilities/index.tsx
  src/pages/Applicant/EditableProfile/EditableCapabilities/interface.tsx
  src/pages/Applicant/EditableProfile/EditableCapabilities/styles.module.scss
  src/pages/Applicant/EditableProfile/EditableCareers/component.tsx
  src/pages/Applicant/EditableProfile/EditableCareers/container.tsx
  src/pages/Applicant/EditableProfile/EditableCareers/index.tsx
  src/pages/Applicant/EditableProfile/EditableCareers/interface.tsx
  src/pages/Applicant/EditableProfile/EditableCareers/styles.module.scss
  src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/index.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/interface.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/styles.module.scss
  src/pages/Applicant/EditableProfile/Title/container.tsx
  src/pages/Applicant/EditableProfile/Title/index.tsx
  src/pages/Applicant/EditableProfile/index.tsx
  src/pages/Applicant/Profile/CapabilitiesDetail/component.tsx
  src/pages/Applicant/Profile/CapabilitiesDetail/index.tsx
  src/pages/Applicant/Profile/CapabilitiesDetail/interface.tsx
  src/pages/Applicant/Profile/CareersDetail/component.tsx
  src/pages/Applicant/Profile/CareersDetail/container.tsx
  src/pages/Applicant/Profile/CareersDetail/index.tsx
  src/pages/Applicant/Profile/CareersDetail/interface.tsx
  src/pages/Applicant/Profile/Detail/component.tsx
  src/pages/Applicant/Profile/Detail/container.tsx
  src/pages/Applicant/Profile/Detail/index.tsx
  src/pages/Applicant/Profile/Detail/interface.tsx
  src/pages/Applicant/Profile/Detail/styles.module.scss
  src/pages/Applicant/Profile/Title/container.tsx
  src/pages/Applicant/Profile/Title/index.tsx
  src/pages/Applicant/Profile/index.tsx
  src/pages/Applicant/routes.tsx
  src/pages/Company/CompanyDetail/index.tsx
  src/pages/Company/CompanyTitle/index.tsx
  src/pages/Company/Profile/Detail/component.tsx
  src/pages/Company/Profile/Detail/container.tsx
  src/pages/Company/Profile/Detail/index.tsx
  src/pages/Company/Profile/Detail/interface.tsx
  src/pages/Company/Profile/Detail/styles.module.scss
  src/pages/Company/Profile/Title/container.tsx
  src/pages/Company/Profile/Title/index.tsx
  src/pages/Company/Profile/index.tsx
  src/pages/Company/index.tsx
  src/pages/Company/routes.tsx
  src/routes.tsx
Labels: convention

#27 Company detail redesign
  src/components/Detail/DetailByLine/styles.module.scss
  src/components/Detail/DetailContactMe/styles.module.scss
  src/components/Detail/DetailDescription/styles.module.scss
  src/components/Detail/DetailHeadline/styles.module.scss
  src/components/Detail/DetailMainContainer/styles.module.scss
  src/components/Detail/DetailTitle/component.tsx
  src/components/Detail/DetailTitle/index.tsx
  src/components/Detail/DetailTitle/interface.tsx
  src/components/Detail/DetailTitle/styles.module.scss
  src/components/InputEditable/styles.module.scss
  src/components/NavBar/styles.module.scss
  src/components/SubmitButton/styles.module.scss
  src/components/Title/component.tsx
  src/components/Title/index.tsx
  src/components/Title/interface.tsx
  src/components/Title/styles.module.scss
  src/pages/Applicant/EditableProfile/EditableCareers/styles.module.scss
  src/pages/Applicant/EditableProfile/Title/container.tsx
  src/pages/Applicant/Profile/Detail/styles.module.scss
  src/pages/Applicant/Profile/Title/container.tsx
  src/pages/Company/Profile/Detail/styles.module.scss
  src/pages/Company/Profile/Title/container.tsx
  src/styles/_detailsVariables.scss
  src/styles/_hoverShadow.scss
  src/styles/_variables.scss
  src/styles/base.scss
  src/styles/mixins/_card.scss
  src/styles/mixins/_subtitle.scss
  src/styles/mixins/_title.scss
Labels: feature

#29 Move mainContent to its own component
  package.json
  src/components/MainContent/component.tsx
  src/components/MainContent/index.tsx
  src/components/MainContent/styles.module.scss
  src/components/NavBar/styles.module.scss
  src/components/Window/component.tsx
  src/components/Window/index.tsx
  src/index.tsx
  src/pages/Applicant/EditableProfile/index.tsx
  src/pages/Applicant/Profile/index.tsx
  src/pages/Company/Profile/index.tsx
  src/styles/base.scss
  yarn.lock
Labels: feature

#28 Feature/96 applicants list
  src/components/ListItem/component.tsx
  src/components/ListItem/index.tsx
  src/components/Title/interface.tsx
  src/graphql/queries/getApplicants.graphql
  src/graphql/queries/index.ts
  src/pages/Applicant/List/Applicants/component.tsx
  src/pages/Applicant/List/Applicants/container.tsx
  src/pages/Applicant/List/Applicants/index.tsx
  src/pages/Applicant/List/Applicants/interface.tsx
  src/pages/Applicant/List/Title/container.tsx
  src/pages/Applicant/List/Title/index.tsx
  src/pages/Applicant/List/index.tsx
  src/pages/Applicant/routes.tsx
Labels: feature

#30 Feature/97 add style to applicants list
  src/components/Button/styles.module.scss
  src/components/ListItem/component.tsx
  src/components/ListItem/styles.module.scss
  src/pages/Applicant/List/Applicants/component.tsx
  src/pages/Applicant/List/Applicants/styles.module.scss
  src/pages/Applicant/List/Title/container.tsx
Labels: feature

#35 Feat: Use uuids for applicant links
  src/graphql/queries/getApplicant.graphql
  src/graphql/queries/index.ts
  src/interfaces/Applicant/index.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/List/Applicants/component.tsx
  src/pages/Applicant/List/Applicants/container.tsx
  src/pages/Applicant/List/Applicants/interface.tsx
  src/pages/Applicant/Profile/Detail/container.tsx
  src/pages/Applicant/SignUp/component.tsx
  src/routesBuilder.tsx
Labels: refactor

#36 Feature/85 fix mobile style
  src/components/CompanyLogo/interface.tsx
  src/components/CompanyLogo/styles.module.scss
  src/graphql/queries/getApplicants.graphql
  src/pages/Applicant/List/Applicants/styles.module.scss
  src/pages/Company/List/Companies/component.tsx
  src/pages/Company/List/Companies/styles.module.scss
  src/styles/_list.scss
Labels: refactor

#37 Feature/93 redesign register form style
  src/pages/Applicant/SignUp/component.tsx
  src/pages/Applicant/SignUp/container.tsx
  src/pages/Applicant/SignUp/index.tsx
  src/pages/Applicant/SignUp/styles.module.scss
  src/pages/Applicant/routes.tsx
Labels: refactor

#39 Feature/91 refactor applicant detail
  src/components/Button/styles.module.scss
  src/components/Detail/DetailByLine/index.tsx
  src/components/Detail/DetailByLine/styles.module.scss
  src/components/Detail/DetailHeadline/styles.module.scss
  src/components/Detail/ItemsDetail/component.tsx
  src/components/Detail/ItemsDetail/styles.module.scss
  src/components/Tag/component.tsx
  src/components/Tag/index.tsx
  src/components/Tag/interface.tsx
  src/components/Tag/styles.module.scss
  src/pages/Applicant/Profile/CapabilitiesDetail/component.tsx
  src/pages/Applicant/Profile/CapabilitiesDetail/interface.tsx
  src/pages/Applicant/Profile/CapabilitiesDetail/styles.module.scss
  src/pages/Applicant/Profile/CareersDetail/component.tsx
  src/pages/Applicant/Profile/CareersDetail/container.tsx
  src/pages/Applicant/Profile/CareersDetail/interface.tsx
  src/pages/Applicant/Profile/Detail/component.tsx
  src/pages/Applicant/Profile/Detail/styles.module.scss
  src/pages/Applicant/Profile/SectionDetail/component.tsx
  src/pages/Applicant/Profile/SectionDetail/index.tsx
  src/pages/Applicant/Profile/SectionDetail/interface.tsx
  src/pages/Applicant/Profile/SectionDetail/styles.module.scss
  src/styles/mixins/_text.scss
Labels: refactor

#40 Feature/91 refactor applicant interface
  src/components/Detail/DetailDescription/index.tsx
  src/interfaces/Applicant/index.tsx
  src/pages/Applicant/Profile/Detail/component.tsx
  src/pages/Applicant/Profile/Detail/container.tsx
Labels: refactor

#41 Feature/91 add links to applicant detail
  src/components/Links/component.tsx
  src/components/Links/index.tsx
  src/components/Links/interface.tsx
  src/components/Links/styles.module.scss
  src/interfaces/Applicant/index.tsx
  src/pages/Applicant/Profile/Detail/component.tsx
  src/pages/Applicant/Profile/Detail/container.tsx
Labels: feature

#42 Move repeated variables to _variables.scc file
  src/components/Detail/ItemsDetail/styles.module.scss
  src/components/Detail/ItemsDetailEditable/styles.module.scss
  src/pages/Applicant/EditableProfile/EditableCapabilities/styles.module.scss
  src/styles/_detailsVariables.scss
  src/styles/_variables.scss
  src/styles/base.scss
Labels: refactor

#38 Reimplement Selector with material ui Autocomplete component
  package.json
  src/components/Button/interface.ts
  src/components/CareerSelector/compontent.tsx
  src/components/CareerSelector/container.tsx
  src/components/CareerSelector/index.tsx
  src/components/CareerSelector/interface.ts
  src/components/Selector/index.tsx
  src/components/Selector/styles.module.scss
  src/pages/Applicant/SignUp/component.tsx
  src/pages/Applicant/SignUp/container.tsx
  src/pages/Applicant/SignUp/interfaces.ts
  src/pages/Applicant/SignUp/translations.ts
  src/pages/Applicant/SignUp/utils.ts
  yarn.lock
Labels: refactor

#44 Rename component from DetailByLine to Subtitle
  src/components/Detail/DetailByLine/component.tsx
  src/components/Detail/DetailByLine/index.tsx
  src/components/Detail/DetailByLine/interface.tsx
  src/components/Detail/ItemsDetail/component.tsx
  src/components/Detail/ItemsDetail/styles.module.scss
  src/components/Subtitle/component.tsx
  src/components/Subtitle/index.tsx
  src/components/Subtitle/interface.tsx
  src/components/Subtitle/styles.module.scss
  src/components/Title/component.tsx
  src/components/Title/styles.module.scss
  src/pages/Applicant/List/Applicants/component.tsx
  src/pages/Applicant/List/Applicants/styles.module.scss
  src/pages/Applicant/Profile/CapabilitiesDetail/component.tsx
  src/pages/Applicant/Profile/CapabilitiesDetail/styles.module.scss
  src/pages/Applicant/Profile/SectionDetail/component.tsx
  src/pages/Company/List/Companies/component.tsx
  src/pages/Company/List/Companies/styles.module.scss
  src/pages/Company/Profile/Detail/component.tsx
Labels: refactor

#43 Migrate all form fields to material UI
  package.json
  src/App.tsx
  src/components/CareerSelector/compontent.tsx
  src/components/TextInput/index.tsx
  src/components/TextInput/interface.ts
  src/components/TextInput/styles.module.scss
  src/materialUITheme.ts
  src/pages/Applicant/SignUp/component.tsx
  src/pages/Applicant/SignUp/styles.module.scss
  yarn.lock
Labels: feature

#45 Change Subtitle component to recieve children
  src/components/Detail/DetailContactMe/component.tsx
  src/components/Detail/DetailContactMe/styles.module.scss
  src/components/Detail/ItemsDetail/component.tsx
  src/components/Detail/ItemsDetail/styles.module.scss
  src/components/Links/component.tsx
  src/components/Links/styles.module.scss
  src/components/Subtitle/component.tsx
  src/components/Subtitle/interface.tsx
  src/components/Subtitle/styles.module.scss
  src/components/Title/component.tsx
  src/components/Title/styles.module.scss
  src/pages/Applicant/List/Applicants/component.tsx
  src/pages/Applicant/List/Applicants/styles.module.scss
  src/pages/Applicant/Profile/CapabilitiesDetail/component.tsx
  src/pages/Applicant/Profile/CapabilitiesDetail/styles.module.scss
  src/pages/Applicant/Profile/SectionDetail/component.tsx
  src/pages/Company/List/Companies/component.tsx
  src/pages/Company/List/Companies/styles.module.scss
  src/pages/Company/Profile/Detail/component.tsx
  src/styles/mixins/_subtitle.scss
Labels: refactor

#47 Create LoadingSpinner component and use it in ApplicantDetail page
  src/components/ListTitle/container.tsx
  src/components/LoadingSpinner/component.tsx
  src/components/LoadingSpinner/index.tsx
  src/components/LoadingSpinner/styles.module.scss
  src/materialUITheme.ts
  src/pages/Applicant/Profile/Detail/component.tsx
  src/pages/Applicant/Profile/Detail/container.tsx
  src/pages/Applicant/Profile/Detail/interface.tsx
  src/pages/Applicant/Profile/Title/container.tsx
Labels: feature

#46 Update Sign Up styles
  src/components/AddButton/index.tsx
  src/components/AddButton/styles.module.scss
  src/components/Button/styles.module.scss
  src/components/CareerSelector/compontent.tsx
  src/components/CareerSelector/container.tsx
  src/components/CareerSelector/styles.module.scss
  src/components/FormSection/index.tsx
  src/components/FormSection/styles.module.scss
  src/components/NavBar/component.tsx
  src/components/NavBar/container.tsx
  src/components/NavBar/interface.tsx
  src/components/RemoveButton/index.tsx
  src/components/RemoveButton/styles.module.scss
  src/components/Selector/index.tsx
  src/components/TextInput/index.tsx
  src/components/TextInput/styles.module.scss
  src/pages/Applicant/EditableProfile/EditableCareers/component.tsx
  src/pages/Applicant/SignUp/component.tsx
  src/pages/Applicant/SignUp/interfaces.ts
  src/pages/Applicant/SignUp/styles.module.scss
  src/pages/Applicant/SignUp/translations.ts
  src/pages/Applicant/SignUp/utils.ts
  src/routesBuilder.tsx
Labels: feature

#49 Add spinner for companies and applicants list
  src/components/ListTitle/container.tsx
  src/pages/Applicant/List/Applicants/component.tsx
  src/pages/Applicant/List/Applicants/container.tsx
  src/pages/Applicant/List/Applicants/interface.tsx
  src/pages/Company/List/Companies/component.tsx
  src/pages/Company/List/Companies/container.tsx
  src/pages/Company/List/Companies/interface.tsx
  src/pages/Company/Profile/Detail/component.tsx
  src/pages/Company/Profile/Detail/container.tsx
  src/pages/Company/Profile/Detail/interface.tsx
  src/pages/Company/Profile/Title/container.tsx
Labels: feature

#50 Feature/107 add spinner to components that use loading and remove home page and replace to for applicants list
  src/components/Logo/index.tsx
  src/components/Logo/logoFiuba.png
  src/components/Logo/styles.module.scss
  src/pages/Applicant/EditableProfile/EditableCareers/container.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/interface.tsx
  src/pages/Applicant/List/Applicants/container.tsx
  src/pages/Applicant/Profile/Detail/container.tsx
  src/pages/Applicant/Profile/Title/container.tsx
  src/pages/Applicant/SignUp/component.tsx
  src/pages/Applicant/SignUp/container.tsx
  src/pages/Applicant/SignUp/interfaces.ts
  src/pages/Company/Profile/Detail/container.tsx
  src/pages/Home/index.tsx
  src/pages/Home/styles.module.scss
  src/pages/Loading/index.tsx
  src/pages/Loading/styles.module.scss
  src/routesBuilder.tsx
  src/test/App.test.tsx
Labels: feature
