Repository fiuba-laboral-v2/front-end, pull requests merged in 2020-07, with the labels that each got.

#168 Add schema generate configuration
  package.json
  src/ApolloClient.ts
  src/config/Configuration.ts
  src/config/codegen.yml
  src/config/configurationVariables.ts
  src/config/fragmentTypes.json
  src/config/index.ts
  src/routes/routes.tsx
  yarn.lock
Labels: feature

#169 Add Applicant to the task list
  package.json
  src/graphql/queries/getPendingEntites.graphql
  src/graphql/queries/getPendingEntities.graphql
  src/graphql/queries/index.ts
  src/graphql/typenames/index.ts
  src/interfaces/Approvable/index.ts
  src/pages/Admin/Home/Dashboard/ApplicantIcon/index.tsx
  src/pages/Admin/Home/Dashboard/ApplicantIcon/styles.module.scss
  src/pages/Admin/Home/Dashboard/CompanyIcon/index.tsx
  src/pages/Admin/Home/Dashboard/CompanyIcon/styles.module.scss
  src/pages/Admin/Home/Dashboard/Menu/Tab/index.tsx
  src/pages/Admin/Home/Dashboard/Menu/Tab/styles.module.scss
  src/pages/Admin/Home/Dashboard/Menu/component.tsx
  src/pages/Admin/Home/Dashboard/Menu/interfaces.ts
  src/pages/Admin/Home/Dashboard/Menu/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskDetail/component.tsx
  src/pages/Admin/Home/Dashboard/TaskList/ApprovableEntity/component.tsx
Labels: feature

#170 Feature/approvable actions translations
  src/components/ErrorPage/index.tsx
  src/interfaces/ApprovalActions/index.ts
  src/models/Window.ts
  src/models/hooks/snackbar/useShowError.tsx
  src/models/hooks/snackbar/useShowSuccess.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/CompanyDetailInfo/container.tsx
  src/pages/Applicant/OfferDetail/container.tsx
Labels: feature

#162 Agregado del detalle en el registro de una empresa
  src/components/CompanyDetail/index.tsx
  src/components/Detail/DetailMainContainer/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/CompanyDetailContent/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/CompanyDetailContent/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskDetail/CompanyDetailInfo/Actions/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/CompanyDetailInfo/Actions/index.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/CompanyDetailInfo/Actions/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskDetail/CompanyDetailInfo/MainTitle/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/CompanyDetailInfo/MainTitle/index.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/CompanyDetailInfo/MainTitle/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskDetail/CompanyDetailInfo/UserDetails/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/CompanyDetailInfo/UserDetails/index.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/CompanyDetailInfo/UserDetails/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskDetail/CompanyDetailInfo/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/CompanyDetailInfo/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/CompanyDetailInfo/styles.module.scss
Labels: feature, wip

#171 Add ApplicantDetailContent
  src/graphql/queries/getApplicant.graphql
  src/pages/Admin/Home/Dashboard/TaskDetail/Applicant/ApplicantDetailContent/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Applicant/ApplicantDetailContent/index.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailContent/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailContent/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailContent/index.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailContent/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/Actions/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/Actions/index.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/Actions/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/MainTitle/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/MainTitle/index.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/MainTitle/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/UserDetails/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/UserDetails/index.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/UserDetails/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/index.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskDetail/component.tsx
Labels: feature

#172 Refactor ApplicantDetailContentContainer to receive applicantUuid and…
  src/pages/Admin/Home/Dashboard/TaskDetail/Applicant/ApplicantDetailContent/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailContent/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/component.tsx
Labels: refactor

#175 Feature/209 get pending entities filter
  src/components/Checkbox/index.tsx
  src/graphql/queries/getPendingEntities.graphql
  src/interfaces/Approvable/index.ts
  src/models/hooks/queries/usePendingEntities.ts
  src/models/hooks/queries/useTranslations.ts
  src/models/hooks/useQuery.ts
  src/pages/Admin/Home/Dashboard/Menu/ApprovableTypeTab/component.tsx
  src/pages/Admin/Home/Dashboard/Menu/ApprovableTypeTab/container.tsx
  src/pages/Admin/Home/Dashboard/Menu/ApprovableTypeTab/index.tsx
  src/pages/Admin/Home/Dashboard/Menu/ApprovableTypeTab/interfaces.ts
  src/pages/Admin/Home/Dashboard/Menu/Tab/index.tsx
  src/pages/Admin/Home/Dashboard/Menu/Tab/styles.module.scss
  src/pages/Admin/Home/Dashboard/Menu/TypeFilter/component.tsx
  src/pages/Admin/Home/Dashboard/Menu/TypeFilter/container.tsx
  src/pages/Admin/Home/Dashboard/Menu/TypeFilter/index.ts
  src/pages/Admin/Home/Dashboard/Menu/TypeFilter/interfaces.ts
  src/pages/Admin/Home/Dashboard/Menu/component.tsx
  src/pages/Admin/Home/Dashboard/Menu/container.tsx
  src/pages/Admin/Home/Dashboard/Menu/interfaces.ts
  src/pages/Admin/Home/Dashboard/TaskList/container.tsx
  src/pages/Admin/Home/Dashboard/TaskList/interface.ts
  src/pages/Admin/Home/Dashboard/component.tsx
  src/pages/Admin/Home/Dashboard/container.tsx
  src/pages/Admin/Home/Dashboard/index.tsx
  tsconfig.json
Labels: feature

#176 Fix/209 pending entities filter style
  src/components/Checkbox/index.tsx
  src/components/Checkbox/styles.module.scss
  src/pages/Admin/Home/Dashboard/ApplicantIcon/styles.module.scss
  src/pages/Admin/Home/Dashboard/CompanyIcon/styles.module.scss
  src/pages/Admin/Home/Dashboard/Menu/ApprovableTypeTab/component.tsx
  src/pages/Admin/Home/Dashboard/Menu/ApprovableTypeTab/container.tsx
  src/pages/Admin/Home/Dashboard/Menu/ApprovableTypeTab/interfaces.ts
  src/pages/Admin/Home/Dashboard/Menu/Tab/index.tsx
  src/pages/Admin/Home/Dashboard/Menu/Tab/styles.module.scss
  src/pages/Admin/Home/Dashboard/Menu/TypeFilter/component.tsx
  src/pages/Admin/Home/Dashboard/Menu/TypeFilter/container.tsx
  src/pages/Admin/Home/Dashboard/Menu/TypeFilter/interfaces.ts
  src/pages/Admin/Home/Dashboard/Menu/TypeFilter/styles.module.scss
  src/styles/_variables.scss
Labels: feature

#180 Agregado de translations a los botones de actions
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/index.tsx
Labels: feature

#181 Fix spacing in applicant task detail
  src/components/CompanyDetail/index.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailContent/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailContent/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskDetail/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/styles.module.scss
Labels: fix

#183 Add updateApplicantApprovalStatus mutation to update applicant status
  src/graphql/mutations/index.ts
  src/graphql/mutations/updateApplicantApprovalStatus.graphql
  src/models/hooks/index.ts
  src/models/hooks/mutations/index.ts
  src/models/hooks/mutations/useUpdateApprovableEntityStatus.ts
  src/models/hooks/mutations/useUpdateCompanyApprovalStatus.ts
  src/models/hooks/useUpdateApprovable.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/Applicant/ApplicantDetailInfo/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/component.tsx
Labels: feature

#187 Rename hook from useUpdateApprovable to useUpdateApprovableStatus and…
  src/models/hooks/index.ts
  src/models/hooks/mutations/index.ts
  src/models/hooks/mutations/useUpdateApprovableStatus.ts
  src/models/hooks/mutations/useUpdateApprovableStatusMutation.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/Applicant/ApplicantDetailInfo/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/container.tsx
Labels: refactor

#188 Rename graphql query from getPendingEntities to getApprovables and ad…
  src/graphql/queries/getApprovables.graphql
  src/graphql/queries/index.ts
  src/interfaces/Approvable/index.ts
  src/models/hooks/queries/index.ts
  src/models/hooks/queries/useGetApprovables.ts
  src/models/hooks/queries/usePendingEntities.ts
  src/pages/Admin/Home/Dashboard/Menu/interfaces.ts
  src/pages/Admin/Home/Dashboard/component.tsx
  src/pages/Admin/Home/Dashboard/container.tsx
Labels: feature

#189 Feature/218 rename aprovables
  src/config/fragmentTypes.json
  src/graphql/queries/getAdminTasks.graphql
  src/graphql/queries/index.ts
  src/interfaces/AdminTask/index.ts
  src/models/CurrentAdminTask.ts
  src/models/CurrentApplicant.ts
  src/models/CurrentCompany.ts
  src/models/hooks/mutations/index.ts
  src/models/hooks/mutations/useUpdateAdminTaskStatus.ts
  src/models/hooks/mutations/useUpdateAdminTaskStatusMutation.ts
  src/models/hooks/queries/index.ts
  src/models/hooks/queries/useGetAdminTasks.ts
  src/models/hooks/queries/useGetApprovables.ts
  src/pages/Admin/Home/Dashboard/Menu/AdminTaskTypeTab/component.tsx
  src/pages/Admin/Home/Dashboard/Menu/AdminTaskTypeTab/container.tsx
  src/pages/Admin/Home/Dashboard/Menu/AdminTaskTypeTab/index.tsx
  src/pages/Admin/Home/Dashboard/Menu/AdminTaskTypeTab/interfaces.ts
  src/pages/Admin/Home/Dashboard/Menu/ApprovableTypeTab/index.tsx
  src/pages/Admin/Home/Dashboard/Menu/ApprovableTypeTab/interfaces.ts
  src/pages/Admin/Home/Dashboard/Menu/TypeFilter/component.tsx
  src/pages/Admin/Home/Dashboard/Menu/TypeFilter/container.tsx
  src/pages/Admin/Home/Dashboard/Menu/TypeFilter/interfaces.ts
  src/pages/Admin/Home/Dashboard/Menu/TypeFilter/styles.module.scss
  src/pages/Admin/Home/Dashboard/Menu/component.tsx
  src/pages/Admin/Home/Dashboard/Menu/container.tsx
  src/pages/Admin/Home/Dashboard/Menu/interfaces.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/Applicant/ApplicantDetailInfo/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/component.tsx
  src/pages/Admin/Home/Dashboard/TaskList/AdminTask/component.tsx
  src/pages/Admin/Home/Dashboard/TaskList/AdminTask/index.ts
  src/pages/Admin/Home/Dashboard/TaskList/AdminTask/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskList/ListBody/component.tsx
  src/pages/Admin/Home/Dashboard/TaskList/ListInfo/component.tsx
  src/pages/Admin/Home/Dashboard/TaskList/component.tsx
  src/pages/Admin/Home/Dashboard/TaskList/container.tsx
  src/pages/Admin/Home/Dashboard/TaskList/interface.ts
  src/pages/Admin/Home/Dashboard/component.tsx
  src/pages/Admin/Home/Dashboard/container.tsx
Labels: refactor

#190 Feature/219 status filter
  src/pages/Admin/Home/Dashboard/Menu/AdminTaskTypeTab/component.tsx
  src/pages/Admin/Home/Dashboard/Menu/AdminTaskTypeTab/container.tsx
  src/pages/Admin/Home/Dashboard/Menu/AdminTaskTypeTab/index.tsx
  src/pages/Admin/Home/Dashboard/Menu/AdminTaskTypeTab/interfaces.ts
  src/pages/Admin/Home/Dashboard/Menu/Filter/index.tsx
  src/pages/Admin/Home/Dashboard/Menu/Filter/styles.module.scss
  src/pages/Admin/Home/Dashboard/Menu/StatusFilter/component.tsx
  src/pages/Admin/Home/Dashboard/Menu/StatusFilter/container.tsx
  src/pages/Admin/Home/Dashboard/Menu/StatusFilter/index.tsx
  src/pages/Admin/Home/Dashboard/Menu/StatusFilter/interfaces.ts
  src/pages/Admin/Home/Dashboard/Menu/StatusFilter/styles.module.scss
  src/pages/Admin/Home/Dashboard/Menu/Tab/index.tsx
  src/pages/Admin/Home/Dashboard/Menu/Tab/styles.module.scss
  src/pages/Admin/Home/Dashboard/Menu/TypeFilter/component.tsx
  src/pages/Admin/Home/Dashboard/Menu/TypeFilter/container.tsx
  src/pages/Admin/Home/Dashboard/Menu/TypeFilter/interfaces.ts
  src/pages/Admin/Home/Dashboard/Menu/component.tsx
  src/pages/Admin/Home/Dashboard/Menu/container.tsx
  src/pages/Admin/Home/Dashboard/Menu/interfaces.ts
  src/pages/Admin/Home/Dashboard/Menu/styles.module.scss
Labels: feature

#191 Use interface to avoid repeating translations interface on component …
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/interaces.ts
Labels: refactor

#192 Feature/225 action buttons
  src/graphql/queries/getApplicant.graphql
  src/interfaces/Applicant/index.ts
  src/models/hooks/mutations/useUpdateAdminTaskStatus.ts
  src/models/hooks/mutations/useUpdateAdminTaskStatusMutation.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/interaces.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/Applicant/ApplicantDetailInfo/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Applicant/ApplicantDetailInfo/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/DetailInfo/index.tsx
Labels: feature

#193 Feature/226 label
  src/components/ApprovedLabel/index.tsx
  src/components/Label/index.tsx
  src/components/Label/styles.module.scss
  src/components/PendingLabel/index.tsx
  src/components/RejectedLabel/index.tsx
  src/components/StatusLabel/index.tsx
  src/components/Tag/component.tsx
  src/components/Tag/styles.module.scss
  src/graphql/queries/getAdminTasks.graphql
  src/interfaces/AdminTask/index.ts
  src/models/hooks/index.ts
  src/models/hooks/queries/useTranslations.ts
  src/models/hooks/useStatusText.ts
  src/pages/Admin/Home/Dashboard/TaskList/AdminTask/component.tsx
  src/pages/Admin/Home/Dashboard/TaskList/AdminTask/styles.module.scss
  src/styles/_variables.scss
Labels: feature

#194 Feature/226 detail status label
  src/components/ApplicantDetail/component.tsx
  src/components/ApplicantDetail/container.tsx
  src/components/ApplicantDetail/interface.ts
  src/components/ApplicantDetail/styles.module.scss
  src/components/Card/component.tsx
  src/components/Card/index.tsx
  src/components/Card/styles.module.scss
  src/components/ClickableCard/index.tsx
  src/components/CompanyDetail/index.tsx
  src/components/Detail/DetailMainContainer/component.tsx
  src/components/Detail/DetailMainContainer/index.tsx
  src/components/Detail/DetailMainContainer/styles.module.scss
  src/components/Label/index.tsx
  src/graphql/queries/getMyApplicantProfile.graphql
  src/graphql/queries/getMyCompanyProfile.graphql
  src/pages/Admin/Home/Dashboard/TaskList/AdminTask/component.tsx
  src/pages/Admin/Home/Dashboard/TaskList/ListBody/component.tsx
  src/pages/Applicant/Companies/component.tsx
  src/pages/Applicant/Home/Feed/component.tsx
  src/pages/Applicant/List/Applicants/component.tsx
  src/pages/Applicant/Profile/component.tsx
  src/pages/Company/MyJobApplications/JobApplication/component.tsx
  src/pages/Company/Profile/component.tsx
  src/pages/Public/Register/component.tsx
  src/styles/mixins/_card.scss
Labels: feature

#195 Refactor/226 detail status label
  src/components/ApplicantDetail/component.tsx
  src/components/ApplicantDetail/container.tsx
  src/components/ApplicantDetail/interface.ts
  src/components/ApplicantDetail/styles.module.scss
  src/components/ApprovedLabel/index.tsx
  src/components/CompanyDetail/index.tsx
  src/components/CompanyDetail/styles.module.scss
  src/components/Headline/component.tsx
  src/components/Headline/styles.module.scss
  src/components/Label/index.tsx
  src/components/Label/styles.module.scss
  src/components/PendingLabel/index.tsx
  src/components/RejectedLabel/index.tsx
  src/components/StatusLabel/index.tsx
  src/components/StatusTitle/index.tsx
  src/components/StatusTitle/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskList/AdminTask/component.tsx
  src/pages/Applicant/Profile/component.tsx
  src/pages/Company/Profile/component.tsx
  src/styles/_variables.scss
Labels: refactor

#196 Add pending translation for approvalActions translationGroup
  src/interfaces/ApprovalActions/index.ts
  src/models/hooks/mutations/useUpdateAdminTaskStatus.ts
Labels: fix

#198 Fix/186 edit button
  src/components/ApplicantDetail/component.tsx
  src/components/OfferDetail/component.tsx
Labels: fix

#199 Show updatedAt instead of createdAt in the adminTask card
  src/components/CreatedSince/container.tsx
  src/components/CreatedSince/index.ts
  src/components/OfferDetail/component.tsx
  src/components/TimeHumanizer/index.tsx
  src/components/UpdatedSince/container.tsx
  src/components/UpdatedSince/index.ts
  src/graphql/queries/getAdminTasks.graphql
  src/interfaces/AdminTask/index.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/MainTitle/index.tsx
  src/pages/Admin/Home/Dashboard/TaskList/AdminTask/component.tsx
  src/pages/Applicant/Home/Feed/Offer/Info/component.tsx
  src/pages/Company/MyJobApplications/JobApplication/component.tsx
Labels: fix

#201 Expand detail content
  src/pages/Admin/Home/Dashboard/TaskDetail/styles.module.scss
Labels: fix

#202 Fix mobile layout of offer feed
  src/pages/Applicant/Home/Feed/Offer/Info/component.tsx
  src/pages/Applicant/Home/Feed/Offer/Info/styles.module.scss
Labels: fix
