Repository fiuba-laboral-v2/front-end, pull requests merged in 2020-05, with the labels that each got.

#97 Feature/101 graphql mapped errors
  src/models/RoutesBuilder.ts
  src/models/handleError.ts
  src/models/hooks/useMutation.ts
  src/models/hooks/useQuery.ts
  src/models/hooks/useSaveApplicant.ts
  src/models/hooks/useTranslations.ts
  src/models/omitTypename.ts
  src/pages/Applicant/SignUp/container.tsx
  src/pages/LogIn/LogInForm/container.tsx
  src/pages/LogIn/LogInForm/interface.ts
  src/test/models/handleError.test.ts
  src/test/models/omitTypename.test.ts
Labels: feature

#98 Agregado de validaciones en Edit applicant page
  src/models/hasUniqueValues.ts
  src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/interface.ts
  src/pages/Applicant/EditableProfile/EditableDetail/styles.module.scss
  src/pages/Applicant/SignUp/container.tsx
Labels: feature

#99 Migrate company id to uuid
  src/graphql/queries/getCompanies.graphql
  src/graphql/queries/getCompanyByUuid.graphql
  src/graphql/queries/getOfferByUuid.graphql
  src/graphql/queries/getOffers.graphql
  src/graphql/queries/index.ts
  src/interfaces/Company/index.ts
  src/models/RoutesBuilder.ts
  src/pages/Applicant/OfferDetail/Detail/container.tsx
  src/pages/Company/List/Companies/component.tsx
  src/pages/Company/List/Companies/container.tsx
  src/pages/Company/List/Companies/interface.tsx
  src/pages/Company/Profile/Detail/container.tsx
Labels: refactor

#100 Apply name and surname migration to users table changes
  src/graphql/mutations/saveApplicant.graphql
  src/graphql/mutations/updateApplicant.graphql
  src/graphql/queries/getApplicant.graphql
  src/graphql/queries/getApplicants.graphql
  src/graphql/queries/me.graphql
  src/interfaces/Applicant/index.ts
  src/interfaces/User/index.ts
  src/models/hooks/useSaveApplicant.ts
  src/models/hooks/useUpdateApplicant.ts
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/List/Applicants/component.tsx
  src/pages/Applicant/Profile/Detail/component.tsx
  src/pages/Applicant/SignUp/container.tsx
Labels: refactor

#101 Agregado del campo description a la edicion del applican
  src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/interface.ts
  src/pages/Applicant/EditableProfile/EditableDetail/styles.module.scss
Labels: feature

#102 Fix homepage redirection; Fix error page styles
  src/ApolloClient.ts
  src/components/ErrorPage/styles.module.scss
  src/components/List/index.tsx
  src/components/NavBar/component.tsx
  src/models/RoutesBuilder.ts
  src/models/Session.ts
  src/models/handleError.ts
  src/models/hooks/useQuery.ts
  src/models/hooks/useTranslations.ts
  src/pages/Applicant/Home/Feed/component.tsx
  src/pages/Applicant/Home/Feed/container.tsx
  src/pages/Applicant/OfferDetail/Detail/container.tsx
  src/pages/Home/index.tsx
  src/pages/InternalServerError/index.tsx
  src/pages/InternalServerError/styles.module.scss
  src/pages/LogIn/LogInForm/container.tsx
  src/pages/NotFound/index.tsx
Labels: feature

#103 Adjust type to back end changes
  src/graphql/mutations/updateApplicant.graphql
  src/graphql/queries/getApplicant.graphql
  src/interfaces/Company/index.ts
Labels: refactor

#104 Disable cache on get offer by uuid
  src/pages/Applicant/OfferDetail/Detail/container.tsx
Labels: fix

#107 Feature/145 register public home page
  public/images/logo.png
  src/components/ClickableCard/component.tsx
  src/components/ClickableCard/index.tsx
  src/components/ClickableCard/styles.module.scss
  src/components/ListItem/index.tsx
  src/components/NavBar/component.tsx
  src/components/NavBar/container.tsx
  src/components/NavBar/styles.module.scss
  src/models/RoutesBuilder.ts
  src/pages/Applicant/Home/Feed/component.tsx
  src/pages/Applicant/List/Applicants/component.tsx
  src/pages/Company/List/Companies/component.tsx
  src/pages/LogIn/LogInForm/component.tsx
  src/pages/Register/component.tsx
  src/pages/Register/container.tsx
  src/pages/Register/header.jpg
  src/pages/Register/index.ts
  src/pages/Register/interface.ts
  src/pages/Register/styles.module.scss
  src/routes.tsx
  src/styles/_variables.scss
Labels: feature

#108 Feature/38 company signup
  src/components/UserInput/index.tsx
  src/graphql/mutations/createCompany.graphql
  src/graphql/mutations/index.ts
  src/interfaces/Company/index.ts
  src/models/RoutesBuilder.ts
  src/models/handleError.ts
  src/models/hooks/useCreateCompany.ts
  src/models/hooks/useSaveApplicant.ts
  src/pages/Company/SignUp/component.tsx
  src/pages/Company/SignUp/container.tsx
  src/pages/Company/SignUp/index.tsx
  src/pages/Company/SignUp/interface.ts
  src/pages/Company/SignUp/styles.module.scss
  src/pages/Company/routes.tsx
  src/pages/Register/container.tsx
Labels: feature

#109 Feature/155 create offer
  src/pages/Company/CreateOffer/component.tsx
  src/pages/Company/CreateOffer/container.tsx
  src/pages/Company/CreateOffer/index.ts
  src/pages/Company/CreateOffer/interface.ts
  src/pages/Company/CreateOffer/styles.module.scss
  src/pages/Company/routes.tsx
Labels: feature

#110 Add translations to create offer; Fix translations error redirection
  src/pages/Applicant/OfferDetail/OfferCareers/container.tsx
  src/pages/Applicant/OfferDetail/OfferSalary/container.tsx
  src/pages/Applicant/OfferDetail/OfferWorkload/container.tsx
  src/pages/Applicant/Profile/CareersDetail/container.tsx
  src/pages/Applicant/Profile/Title/container.tsx
  src/pages/Applicant/SignUp/container.tsx
  src/pages/Company/CreateOffer/container.tsx
  src/pages/Company/CreateOffer/interface.ts
  src/pages/Company/Profile/Title/container.tsx
  src/pages/LogIn/LogInForm/container.tsx
Labels: feature, fix

#111 Restructure hooks
  src/models/hooks/index.ts
  src/models/hooks/mutations/index.ts
  src/models/hooks/mutations/useCreateCompany.ts
  src/models/hooks/mutations/useLogin.ts
  src/models/hooks/mutations/useSaveApplicant.ts
  src/models/hooks/mutations/useUpdateApplicant.ts
  src/models/hooks/queries/index.ts
  src/models/hooks/queries/useTranslations.ts
  src/pages/Applicant/SignUp/container.tsx
  src/pages/Company/SignUp/container.tsx
  src/pages/Home/index.tsx
  src/pages/LogIn/LogInForm/component.tsx
  src/pages/LogIn/LogInForm/container.tsx
  src/pages/Register/container.tsx
Labels: refactor

#112 Add create offer form submission logic
  src/graphql/mutations/createOffer.graphql
  src/graphql/mutations/index.ts
  src/models/hooks/mutations/index.ts
  src/models/hooks/mutations/useCreateOffer.ts
  src/pages/Company/CreateOffer/container.tsx
Labels: feature

#113 Validate salary range in create offer form
  src/pages/Company/CreateOffer/component.tsx
  src/pages/Company/CreateOffer/interface.ts
Labels: feature

#114 Feature/38 company input logo
  package.json
  public/images/companyDefaultLogo.png
  src/components/CompanyLogo/component.tsx
  src/components/CompanyLogo/interface.tsx
  src/components/CompanyLogoInput/index.tsx
  src/components/ImageUpload/index.tsx
  src/pages/Company/SignUp/component.tsx
  src/pages/Company/SignUp/interface.ts
  yarn.lock
Labels: feature

#115 Use UserInput Component in applicant sign up
  src/interfaces/User/index.ts
  src/models/hooks/mutations/useCreateCompany.ts
  src/models/hooks/mutations/useSaveApplicant.ts
  src/pages/Applicant/SignUp/component.tsx
  src/pages/Applicant/SignUp/container.tsx
  src/pages/Applicant/SignUp/interface.ts
  src/pages/Company/SignUp/component.tsx
  src/pages/Company/SignUp/container.tsx
  src/pages/Company/SignUp/interface.ts
Labels: feature

#117 Add hover to company logo input
  public/images/companyDefaultLogo.png
  public/images/imageUpload.png
  src/components/CompanyLogo/component.tsx
  src/components/CompanyLogoInput/index.tsx
  src/components/CompanyLogoInput/styles.module.scss
Labels: feature

#118 Add CompanyLogoInput translations
  src/components/CompanyLogo/component.tsx
  src/components/CompanyLogo/interface.tsx
  src/components/CompanyLogoInput/component.tsx
  src/components/CompanyLogoInput/container.tsx
  src/components/CompanyLogoInput/index.ts
  src/components/CompanyLogoInput/interfaces.ts
  src/pages/Company/SignUp/container.tsx
Labels: feature

#119 Make Redirect component push by default
  src/components/CompanyLogoInput/container.tsx
  src/components/Redirect/index.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/Home/Feed/container.tsx
  src/pages/Applicant/List/Applicants/container.tsx
  src/pages/Applicant/OfferDetail/Detail/container.tsx
  src/pages/Applicant/OfferDetail/OfferCareers/container.tsx
  src/pages/Applicant/OfferDetail/OfferSalary/container.tsx
  src/pages/Applicant/OfferDetail/OfferWorkload/container.tsx
  src/pages/Applicant/Profile/CareersDetail/container.tsx
  src/pages/Applicant/Profile/Detail/container.tsx
  src/pages/Applicant/Profile/Title/container.tsx
  src/pages/Applicant/SignUp/container.tsx
  src/pages/Company/CreateOffer/container.tsx
  src/pages/Company/List/Companies/container.tsx
  src/pages/Company/Profile/Title/container.tsx
  src/pages/Company/SignUp/container.tsx
  src/pages/Home/index.tsx
  src/pages/LogIn/LogInForm/container.tsx
  src/pages/Register/container.tsx
Labels: refactor

#120 Update the cache correctly on job application creation
  src/models/handleError.ts
  src/pages/Applicant/OfferDetail/Detail/component.tsx
  src/pages/Applicant/OfferDetail/Detail/container.tsx
  src/pages/Applicant/OfferDetail/Detail/interface.ts
Labels: feature

#122 Feature/158 job applications
  .travis.yml
  src/components/NavBar/component.tsx
  src/components/NavBar/interface.ts
  src/graphql/queries/getJobApplicationsByCompany.graphql
  src/graphql/queries/index.ts
  src/interfaces/JobApplication/index.ts
  src/models/RoutesBuilder.ts
  src/models/handleError.ts
  src/pages/Company/MyJobApplications/JobApplication/component.tsx
  src/pages/Company/MyJobApplications/JobApplication/index.ts
  src/pages/Company/MyJobApplications/JobApplication/interfaces.ts
  src/pages/Company/MyJobApplications/JobApplication/styles.module.scss
  src/pages/Company/MyJobApplications/component.tsx
  src/pages/Company/MyJobApplications/container.tsx
  src/pages/Company/MyJobApplications/index.tsx
  src/pages/Company/routes.tsx
Labels: feature

#125 Add createOffer to navBar
  src/components/NavBar/component.tsx
  src/components/NavBar/interface.ts
Labels: feature

#124 Add CompanyRoute
  src/graphql/queries/getCurrentUser.graphql
  src/models/hooks/queries/useCurrentUser.ts
  src/routes/ApplicantRoute.tsx
  src/routes/CompanyRoute.tsx
  src/routes/UserRoute.tsx
  src/routes/routes.tsx
Labels: feature

#126 Feature/158 add mobile style to job application
  src/components/TimeHumanizer/index.tsx
  src/graphql/queries/getMyLatestJobApplications.graphql
  src/graphql/queries/index.ts
  src/interfaces/JobApplication/index.ts
  src/pages/Company/MyJobApplications/JobApplication/component.tsx
  src/pages/Company/MyJobApplications/JobApplication/interfaces.ts
  src/pages/Company/MyJobApplications/JobApplication/styles.module.scss
  src/pages/Company/MyJobApplications/component.tsx
  src/pages/Company/MyJobApplications/container.tsx
  src/pages/Company/MyJobApplications/styles.module.scss
Labels: feature

#127 Feature/160 applicant profile query
  src/components/ApplicantDetail/component.tsx
  src/components/ApplicantDetail/container.tsx
  src/components/ApplicantDetail/index.tsx
  src/components/ApplicantDetail/interface.ts
  src/components/ApplicantDetail/styles.module.scss
  src/components/CapabilitiesDetail/component.tsx
  src/components/CapabilitiesDetail/index.tsx
  src/components/CapabilitiesDetail/interface.tsx
  src/components/CareersDetail/component.tsx
  src/components/CareersDetail/container.tsx
  src/components/CareersDetail/index.tsx
  src/components/CareersDetail/interface.tsx
  src/graphql/queries/getCurrentUser.graphql
  src/graphql/queries/getMyApplicantProfile.graphql
  src/graphql/queries/index.ts
  src/models/RoutesBuilder.ts
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/List/Applicants/component.tsx
  src/pages/Applicant/List/Applicants/container.tsx
  src/pages/Applicant/List/Applicants/interface.tsx
  src/pages/Applicant/Profile/Detail/container.tsx
  src/pages/Applicant/Profile/Detail/index.tsx
  src/pages/Applicant/Profile/component.tsx
  src/pages/Applicant/Profile/container.tsx
  src/pages/Applicant/Profile/index.tsx
  src/pages/Applicant/routes.tsx
  src/pages/Company/Applicant/component.tsx
  src/pages/Company/Applicant/container.tsx
  src/pages/Company/Applicant/index.tsx
  src/pages/Company/MyJobApplications/JobApplication/component.tsx
  src/pages/Company/routes.tsx
Labels: feature

#128 Refactor/rename title component
  src/components/Header/component.tsx
  src/components/Header/index.tsx
  src/components/Header/interface.tsx
  src/components/Header/styles.module.scss
  src/components/ListTitle/container.tsx
  src/components/Title/index.tsx
  src/pages/Applicant/Profile/Title/container.tsx
  src/pages/Company/Profile/Title/container.tsx
Labels: refactor

#129 Make navbar links dependent on user type
  src/components/NavBar/component.tsx
  src/components/NavBar/container.tsx
  src/components/NavBar/interface.ts
  src/components/NavBar/styles.module.scss
  src/models/RoutesBuilder.ts
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/List/Applicants/container.tsx
  src/pages/Applicant/routes.tsx
  src/pages/Company/routes.tsx
Labels: feature

#130 Add page for the applicant to see company profile
  src/components/CompanyDetail/index.tsx
  src/components/CompanyDetail/styles.module.scss
  src/graphql/queries/getMyCompanyProfile.graphql
  src/graphql/queries/index.ts
  src/models/RoutesBuilder.ts
  src/pages/Applicant/Companies/component.tsx
  src/pages/Applicant/Companies/container.tsx
  src/pages/Applicant/Companies/index.tsx
  src/pages/Applicant/Companies/interface.tsx
  src/pages/Applicant/Companies/styles.module.scss
  src/pages/Applicant/Company/component.tsx
  src/pages/Applicant/Company/container.tsx
  src/pages/Applicant/Company/index.tsx
  src/pages/Applicant/OfferDetail/Detail/container.tsx
  src/pages/Applicant/routes.tsx
  src/pages/Company/List/index.tsx
  src/pages/Company/Profile/Detail/container.tsx
  src/pages/Company/Profile/Detail/index.tsx
  src/pages/Company/Profile/Detail/interface.tsx
  src/pages/Company/Profile/component.tsx
  src/pages/Company/Profile/container.tsx
  src/pages/Company/Profile/index.tsx
  src/pages/Company/SignUp/container.tsx
  src/pages/Company/routes.tsx
Labels: feature

#131 Add link to my company
  src/components/NavBar/container.tsx
  src/components/NavBar/interface.ts
Labels: feature

#132 Feature/165 offer detail for company
  src/components/Link/index.tsx
  src/components/OfferCareers/component.tsx
  src/components/OfferCareers/container.tsx
  src/components/OfferCareers/index.tsx
  src/components/OfferCareers/interface.tsx
  src/components/OfferCareers/styles.module.scss
  src/components/OfferDetail/component.tsx
  src/components/OfferDetail/index.tsx
  src/components/OfferDetail/styles.module.scss
  src/components/OfferInfo/component.tsx
  src/components/OfferInfo/index.tsx
  src/components/OfferInfo/styles.module.scss
  src/components/OfferInfoItem/component.tsx
  src/components/OfferInfoItem/index.tsx
  src/components/OfferInfoItem/styles.module.scss
  src/components/OfferSalary/component.tsx
  src/components/OfferSalary/container.tsx
  src/components/OfferSalary/index.tsx
  src/components/OfferSalary/interface.tsx
  src/components/OfferSalary/styles.module.scss
  src/components/OfferSalaryInfo/component.tsx
  src/components/OfferSalaryInfo/index.tsx
  src/components/OfferSalaryInfo/styles.module.scss
  src/components/OfferWorkload/component.tsx
  src/components/OfferWorkload/container.tsx
  src/components/OfferWorkload/index.tsx
  src/components/OfferWorkload/interface.tsx
  src/components/OfferWorkload/styles.module.scss
  src/graphql/queries/getCompanyOfferByUuid.graphql
  src/graphql/queries/index.ts
  src/models/RoutesBuilder.ts
  src/pages/Applicant/OfferDetail/Detail/container.tsx
  src/pages/Applicant/OfferDetail/Detail/index.tsx
  src/pages/Applicant/OfferDetail/component.tsx
  src/pages/Applicant/OfferDetail/container.tsx
  src/pages/Applicant/OfferDetail/interfaces.tsx
  src/pages/Company/CreateOffer/container.tsx
  src/pages/Company/MyJobApplications/JobApplication/component.tsx
  src/pages/Company/MyJobApplications/JobApplication/styles.module.scss
  src/pages/Company/OfferDetail/container.tsx
  src/pages/Company/OfferDetail/index.ts
  src/pages/Company/routes.tsx
Labels: feature

#133 Replace component link
  src/components/NavBar/component.tsx
  src/components/OfferDetail/component.tsx
  src/pages/Public/LogIn/LogInForm/component.tsx
Labels: feature

#134 Change updateApplicant by uuid to updateCurrentApplicant
  src/components/ApplicantDetail/component.tsx
  src/components/ApplicantDetail/container.tsx
  src/components/ApplicantDetail/interface.ts
  src/components/ApplicantDetail/styles.module.scss
  src/graphql/mutations/index.ts
  src/graphql/mutations/saveApplicant.graphql
  src/graphql/mutations/updateApplicant.graphql
  src/graphql/mutations/updateCurrentApplicant.graphql
  src/models/RoutesBuilder.ts
  src/models/hooks/mutations/index.ts
  src/models/hooks/mutations/useUpdateCurrentApplicant.ts
  src/models/hooks/queries/index.ts
  src/models/hooks/queries/useMyApplicantProfile.ts
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/List/Applicants/component.tsx
  src/pages/Applicant/List/Applicants/container.tsx
  src/pages/Applicant/List/Applicants/interface.tsx
  src/pages/Applicant/List/Applicants/styles.module.scss
  src/pages/Applicant/Profile/component.tsx
  src/pages/Applicant/Profile/container.tsx
  src/pages/Applicant/Profile/interface.ts
  src/pages/Applicant/SignUp/container.tsx
  src/pages/Applicant/routes.tsx
Labels: refactor

#135 Feature/link companies list to applicant nav bar
  src/components/NavBar/container.tsx
  src/pages/Applicant/Companies/component.tsx
  src/pages/Applicant/Companies/container.tsx
  src/pages/Applicant/Companies/interface.tsx
  src/pages/Applicant/Companies/styles.module.scss
Labels: feature

#136 Restructure urls
  src/components/ApplicantDetail/container.tsx
  src/components/CareersDetail/container.tsx
  src/components/CompanyLogoInput/container.tsx
  src/components/ListTitle/container.tsx
  src/components/NavBar/component.tsx
  src/components/NavBar/container.tsx
  src/components/OfferCareers/container.tsx
  src/components/OfferSalary/container.tsx
  src/components/OfferWorkload/container.tsx
  src/models/RoutesBuilder.ts
  src/pages/Applicant/Companies/container.tsx
  src/pages/Applicant/Company/container.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/Home/Feed/container.tsx
  src/pages/Applicant/List/Applicants/component.tsx
  src/pages/Applicant/List/Applicants/container.tsx
  src/pages/Applicant/List/Applicants/interface.tsx
  src/pages/Applicant/OfferDetail/container.tsx
  src/pages/Applicant/Profile/Title/container.tsx
  src/pages/Applicant/Profile/container.tsx
  src/pages/Applicant/SignUp/container.tsx
  src/pages/Applicant/routes.tsx
  src/pages/Company/Applicant/container.tsx
  src/pages/Company/CreateOffer/container.tsx
  src/pages/Company/MyJobApplications/container.tsx
  src/pages/Company/OfferDetail/container.tsx
  src/pages/Company/Profile/Title/container.tsx
  src/pages/Company/Profile/container.tsx
  src/pages/Company/SignUp/container.tsx
  src/pages/Company/routes.tsx
  src/pages/Public/Home/index.tsx
  src/pages/Public/LogIn/LogInForm/component.tsx
  src/pages/Public/LogIn/LogInForm/container.tsx
  src/pages/Public/NotFound/index.tsx
  src/pages/Public/Register/container.tsx
  src/pages/Public/routes.tsx
  src/routes/UserRoute.tsx
  src/routes/routes.tsx
Labels: refactor

#140 Company offer edit
  src/components/EditOffer/index.tsx
  src/components/EditOffer/styles.module.scss
  src/graphql/mutations/editOffer.graphql
  src/graphql/mutations/index.ts
  src/models/RoutesBuilder.ts
  src/models/hooks/mutations/index.ts
  src/models/hooks/mutations/useEditOffer.ts
  src/pages/Company/CreateOffer/container.tsx
  src/pages/Company/CreateOffer/interface.ts
  src/pages/Company/EditOffer/container.tsx
  src/pages/Company/EditOffer/index.ts
  src/pages/Company/OfferDetail/container.tsx
  src/pages/Company/routes.tsx
Labels: feature

#139 Add EditableProfile page for company
  package.json
  src/components/CompanyDetail/index.tsx
  src/components/CompanyDetail/styles.module.scss
  src/components/CompanyFields/component.tsx
  src/components/CompanyFields/container.tsx
  src/components/CompanyFields/index.ts
  src/components/CompanyFields/interface.ts
  src/components/CompanyLogoInput/component.tsx
  src/components/CompanyLogoInput/container.tsx
  src/components/CompanyLogoInput/interfaces.ts
  src/components/ImageUpload/index.tsx
  src/graphql/mutations/index.ts
  src/graphql/mutations/updateCurrentCompany.graphql
  src/models/RoutesBuilder.ts
  src/models/errorHandlers/createCompanyErrorHandlers.ts
  src/models/errorHandlers/index.ts
  src/models/errorHandlers/saveCompanyErrorHandlers.ts
  src/models/hooks/mutations/index.ts
  src/models/hooks/mutations/useUpdateCurrentCompany.ts
  src/models/hooks/queries/index.ts
  src/models/hooks/queries/useMyCompanyProfile.ts
  src/pages/Company/EditableProfile/component.tsx
  src/pages/Company/EditableProfile/container.tsx
  src/pages/Company/EditableProfile/index.tsx
  src/pages/Company/EditableProfile/interface.tsx
  src/pages/Company/EditableProfile/styles.module.scss
  src/pages/Company/Profile/component.tsx
  src/pages/Company/Profile/container.tsx
  src/pages/Company/Profile/interface.ts
  src/pages/Company/SignUp/component.tsx
  src/pages/Company/SignUp/container.tsx
  src/pages/Company/SignUp/interface.ts
  src/pages/Company/routes.tsx
Labels: feature

#144 Add toast notifications
  package.json
  src/App.tsx
  src/materialUITheme.ts
  src/models/hooks/queries/useTranslations.ts
  src/pages/Applicant/OfferDetail/container.tsx
  src/pages/Public/LogIn/LogInForm/container.tsx
  yarn.lock
Labels: feature
