Repository fiuba-laboral-v2/front-end, pull requests merged in 2020-04, with the labels that each got.

#51 Use uuid to update applicant
  src/graphql/mutations/deleteApplicantCapabilities.graphql
  src/graphql/mutations/deleteApplicantCareers.graphql
  src/graphql/mutations/updateApplicant.graphql
  src/interfaces/Applicant/index.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/Profile/Detail/component.tsx
  src/pages/Applicant/Profile/Detail/container.tsx
Labels: refactor

#52 Feature/93 fix sign up validations
  src/FormikValidator.ts
  src/components/CareerSelector/compontent.tsx
  src/components/Selector/index.tsx
  src/pages/Applicant/SignUp/component.tsx
  src/pages/Applicant/SignUp/container.tsx
  src/pages/Applicant/SignUp/interface.ts
  src/pages/Applicant/SignUp/interfaces.ts
  src/pages/Applicant/SignUp/styles.module.scss
  src/pages/Applicant/SignUp/utils.ts
  src/styles/_variables.scss
Labels: refactor

#54 Feature/108 uppercase queries and mutations
  src/components/CareerSelector/container.tsx
  src/components/FormFooter/container.tsx
  src/components/ListTitle/container.tsx
  src/components/NavBar/container.tsx
  src/graphql/mutations/index.ts
  src/graphql/queries/getApplicantByPadron.graphql
  src/graphql/queries/index.ts
  src/pages/Applicant/EditableProfile/EditableCapabilities/container.tsx
  src/pages/Applicant/EditableProfile/EditableCareers/container.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/EditableProfile/Title/container.tsx
  src/pages/Applicant/List/Applicants/container.tsx
  src/pages/Applicant/Profile/CareersDetail/container.tsx
  src/pages/Applicant/Profile/Detail/container.tsx
  src/pages/Applicant/Profile/Title/container.tsx
  src/pages/Applicant/SignUp/container.tsx
  src/pages/Company/List/Companies/container.tsx
  src/pages/Company/Profile/Detail/container.tsx
  src/pages/Company/Profile/Title/container.tsx
Labels: refactor

#53 Restructure forms to reduce code repetition
  src/components/CareerSelector/compontent.tsx
  src/components/CareerSelector/interface.ts
  src/components/CareerSelector/styles.module.scss
  src/components/FieldSet/index.tsx
  src/components/FieldSet/styles.module.scss
  src/components/FormFooter/component.tsx
  src/components/FormFooter/container.tsx
  src/components/FormFooter/index.tsx
  src/components/FormFooter/interface.tsx
  src/components/FormFooter/styles.module.scss
  src/components/FormSet/index.tsx
  src/components/FormSet/styles.module.scss
  src/components/Selector/index.tsx
  src/components/SubmitButton/component.tsx
  src/components/SubmitButton/index.tsx
  src/components/SubmitButton/interface.tsx
  src/components/SubmitButton/styles.module.scss
  src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/interface.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/styles.module.scss
  src/pages/Applicant/EditableProfile/Title/container.tsx
  src/pages/Applicant/EditableProfile/Title/index.tsx
  src/pages/Applicant/EditableProfile/index.tsx
  src/pages/Applicant/SignUp/component.tsx
  src/pages/Applicant/SignUp/container.tsx
Labels: refactor

#55 Fix css layout
  src/components/AddButton/styles.module.scss
  src/components/CareerSelector/styles.module.scss
  src/components/Detail/DetailHeadline/styles.module.scss
  src/components/Detail/ItemsDetail/styles.module.scss
  src/components/InputEditable/component.tsx
  src/components/Links/component.tsx
  src/components/Links/styles.module.scss
  src/components/NavBar/component.tsx
  src/components/Subtitle/component.tsx
  src/components/Subtitle/styles.module.scss
  src/components/Tag/component.tsx
  src/components/Tag/styles.module.scss
  src/components/Title/styles.module.scss
  src/pages/Applicant/List/Applicants/styles.module.scss
  src/pages/Applicant/Profile/CapabilitiesDetail/styles.module.scss
  src/pages/Applicant/Profile/Detail/component.tsx
  src/pages/Applicant/Profile/Detail/container.tsx
  src/pages/Applicant/Profile/Detail/interface.tsx
  src/pages/Applicant/Profile/Detail/styles.module.scss
  src/pages/Applicant/Profile/SectionDetail/component.tsx
  src/pages/Applicant/Profile/SectionDetail/styles.module.scss
  src/pages/Applicant/SignUp/styles.module.scss
  src/pages/Company/List/Companies/component.tsx
  src/pages/Company/List/Companies/styles.module.scss
  src/pages/Company/Profile/Detail/component.tsx
  src/pages/Company/Profile/Detail/styles.module.scss
  src/styles/mixins/_text.scss
Labels: refactor

#56 Migrate careers to formik
  src/components/CareerSelector/compontent.tsx
  src/components/CareerSelector/container.tsx
  src/components/CareerSelector/interface.ts
  src/components/Detail/ItemsDetail/styles.module.scss
  src/components/EditableField/component.tsx
  src/components/EditableField/container.tsx
  src/components/EditableField/index.tsx
  src/components/EditableField/interface.tsx
  src/components/EditableField/styles.module.scss
  src/components/FormSet/index.tsx
  src/components/InputEditable/component.tsx
  src/components/InputEditable/index.tsx
  src/components/InputEditable/interface.tsx
  src/components/InputEditable/styles.module.scss
  src/components/Selector/index.tsx
  src/interfaces/Applicant/index.tsx
  src/pages/Applicant/EditableProfile/EditableCapabilities/component.tsx
  src/pages/Applicant/EditableProfile/EditableCapabilities/container.tsx
  src/pages/Applicant/EditableProfile/EditableCapabilities/index.tsx
  src/pages/Applicant/EditableProfile/EditableCapabilities/interface.tsx
  src/pages/Applicant/EditableProfile/EditableCapabilities/styles.module.scss
  src/pages/Applicant/EditableProfile/EditableCareers/component.tsx
  src/pages/Applicant/EditableProfile/EditableCareers/container.tsx
  src/pages/Applicant/EditableProfile/EditableCareers/index.tsx
  src/pages/Applicant/EditableProfile/EditableCareers/interface.tsx
  src/pages/Applicant/EditableProfile/EditableCareers/styles.module.scss
  src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/interface.ts
  src/pages/Applicant/EditableProfile/EditableDetail/styles.module.scss
  src/pages/Applicant/Profile/CareersDetail/component.tsx
  src/pages/Applicant/Profile/Detail/styles.module.scss
  src/pages/Applicant/SignUp/component.tsx
  src/pages/Applicant/SignUp/container.tsx
  src/pages/Applicant/SignUp/interface.ts
Labels: feature

#59 Add TextInputs for name and surname
  src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/SignUp/component.tsx
Labels: feature

#57 Add capabilities selector
  src/components/CapabilitiesSelector/compontent.tsx
  src/components/CapabilitiesSelector/index.tsx
  src/components/Selector/BaseSelector/index.tsx
  src/components/Selector/BaseSelector/styles.module.scss
  src/components/Selector/MultipleSelector/index.tsx
  src/components/Selector/MultipleSelector/styles.module.scss
  src/components/Selector/Selector/index.tsx
  src/components/Selector/index.tsx
  src/components/TagSet/component.tsx
  src/components/TagSet/index.tsx
  src/components/TagSet/styles.module.scss
  src/interfaces/Applicant/index.tsx
  src/materialUITheme.ts
  src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/interface.ts
  src/pages/Applicant/Profile/CapabilitiesDetail/component.tsx
  src/pages/Applicant/Profile/Detail/styles.module.scss
Labels: feature

#61 Add sections to applicant edit
  src/components/Selector/BaseSelector/index.tsx
  src/components/Selector/MultipleSelector/index.tsx
  src/components/Selector/Selector/index.tsx
  src/components/TextInput/index.tsx
  src/materialUITheme.ts
  src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/interface.ts
Labels: feature

#62 Feature/92 populate capabilities selector
  package.json
  src/components/CapabilitiesSelector/compontent.tsx
  src/components/CapabilitiesSelector/container.tsx
  src/components/CapabilitiesSelector/index.tsx
  src/components/CapabilitiesSelector/interface.ts
  src/components/CareerSelector/compontent.tsx
  src/components/NavBar/component.tsx
  src/components/Selector/MultipleSelector/index.tsx
  src/graphql/queries/getCapabilities.graphql
  src/graphql/queries/index.ts
  src/interfaces/Applicant/index.ts
  src/interfaces/Capability/index.ts
  src/interfaces/Company/index.ts
  src/materialUITheme.ts
  src/models/FormikValidator.ts
  src/models/RoutesBuilder.ts
  src/models/TextFormatter.ts
  src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/interface.ts
  src/pages/Applicant/List/Applicants/container.tsx
  src/pages/Applicant/Profile/CapabilitiesDetail/interface.tsx
  src/pages/Applicant/Profile/Detail/container.tsx
  src/pages/Applicant/Profile/Title/container.tsx
  src/pages/Applicant/SignUp/component.tsx
  src/pages/Applicant/SignUp/container.tsx
  src/pages/Company/List/Companies/container.tsx
  src/pages/Company/Profile/Detail/container.tsx
  src/pages/Home/index.tsx
  src/test/models/TextFormatter/toUpperCase.test.ts
Labels: feature

#64 Allow deletion of capabilities in applicant edit
  src/components/CapabilitiesSelector/container.tsx
  src/components/Selector/MultipleSelector/index.tsx
  src/components/Tag/component.tsx
  src/components/Tag/interface.tsx
  src/components/Tag/styles.module.scss
  src/components/TagSet/component.tsx
Labels: feature

#63 Feature/123 offer detail
  package.json
  src/components/Button/index.tsx
  src/components/Button/interface.ts
  src/components/Button/styles.module.scss
  src/components/Description/styles.module.scss
  src/components/Detail/DetailHeadline/component.tsx
  src/components/Detail/DetailHeadline/index.tsx
  src/components/Detail/DetailHeadline/interface.tsx
  src/components/Headline/component.tsx
  src/components/Headline/index.tsx
  src/components/Headline/styles.module.scss
  src/components/SectionDetail/component.tsx
  src/components/SectionDetail/index.tsx
  src/components/SectionDetail/styles.module.scss
  src/graphql/queries/getOfferByUuid.graphql
  src/graphql/queries/index.ts
  src/interfaces/Offer/index.tsx
  src/pages/Applicant/OfferDetail/Detail/component.tsx
  src/pages/Applicant/OfferDetail/Detail/container.tsx
  src/pages/Applicant/OfferDetail/Detail/index.tsx
  src/pages/Applicant/OfferDetail/Detail/styles.module.scss
  src/pages/Applicant/OfferDetail/OfferCareers/component.tsx
  src/pages/Applicant/OfferDetail/OfferCareers/container.tsx
  src/pages/Applicant/OfferDetail/OfferCareers/index.tsx
  src/pages/Applicant/OfferDetail/OfferCareers/interface.tsx
  src/pages/Applicant/OfferDetail/OfferCareers/styles.module.scss
  src/pages/Applicant/OfferDetail/OfferInfo/component.tsx
  src/pages/Applicant/OfferDetail/OfferInfo/index.tsx
  src/pages/Applicant/OfferDetail/OfferInfo/styles.module.scss
  src/pages/Applicant/OfferDetail/OfferInfoItem/component.tsx
  src/pages/Applicant/OfferDetail/OfferInfoItem/index.tsx
  src/pages/Applicant/OfferDetail/OfferInfoItem/styles.module.scss
  src/pages/Applicant/OfferDetail/OfferSalary/component.tsx
  src/pages/Applicant/OfferDetail/OfferSalary/container.tsx
  src/pages/Applicant/OfferDetail/OfferSalary/index.tsx
  src/pages/Applicant/OfferDetail/OfferSalary/interface.tsx
  src/pages/Applicant/OfferDetail/OfferSalary/styles.module.scss
  src/pages/Applicant/OfferDetail/OfferWorkload/component.tsx
  src/pages/Applicant/OfferDetail/OfferWorkload/container.tsx
  src/pages/Applicant/OfferDetail/OfferWorkload/index.tsx
  src/pages/Applicant/OfferDetail/OfferWorkload/interface.tsx
  src/pages/Applicant/OfferDetail/OfferWorkload/styles.module.scss
  src/pages/Applicant/OfferDetail/index.tsx
  src/pages/Applicant/Profile/Detail/component.tsx
  src/pages/Applicant/routes.tsx
  src/pages/Company/Profile/Detail/component.tsx
  yarn.lock
Labels: feature

#66 Feature/123 offer detail translations
  src/pages/Applicant/OfferDetail/Detail/component.tsx
  src/pages/Applicant/OfferDetail/Detail/container.tsx
  src/pages/Applicant/OfferDetail/OfferCareers/container.tsx
  src/pages/Applicant/OfferDetail/OfferSalary/container.tsx
  src/pages/Applicant/OfferDetail/OfferWorkload/container.tsx
  src/pages/Applicant/OfferDetail/OfferWorkload/styles.module.scss
Labels: feature

#67 Feature/123 offer detail refactor styles and html tags
  package.json
  src/components/NavBar/styles.module.scss
  src/components/SectionDetail/styles.module.scss
  src/components/Subtitle/styles.module.scss
  src/components/Tag/styles.module.scss
  src/components/TimeHumanizer/index.tsx
  src/pages/Applicant/OfferDetail/Detail/component.tsx
  src/pages/Applicant/OfferDetail/Detail/styles.module.scss
  src/pages/Applicant/OfferDetail/OfferCareers/component.tsx
  src/pages/Applicant/OfferDetail/OfferCareers/styles.module.scss
  src/pages/Applicant/OfferDetail/OfferInfoItem/component.tsx
  src/pages/Applicant/OfferDetail/OfferSalary/component.tsx
  src/pages/Applicant/OfferDetail/OfferSalary/styles.module.scss
  src/pages/Applicant/OfferDetail/OfferSalaryInfo/component.tsx
  src/pages/Applicant/OfferDetail/OfferSalaryInfo/index.tsx
  src/pages/Applicant/OfferDetail/OfferSalaryInfo/styles.module.scss
  src/pages/Applicant/OfferDetail/OfferWorkload/component.tsx
  src/pages/Applicant/OfferDetail/OfferWorkload/styles.module.scss
  src/styles/_variables.scss
  src/styles/base.scss
  src/styles/mixins/_text.scss
  src/styles/mixins/_title.scss
  yarn.lock
Labels: refactor

#69 Feature/122 lista de ofertas
  src/components/ListItem/component.tsx
  src/models/RoutesBuilder.ts
  src/pages/Applicant/Home/Feed/Offer/Info/JobSpecs/SpecItem/index.tsx
  src/pages/Applicant/Home/Feed/Offer/Info/JobSpecs/SpecItem/styles.module.scss
  src/pages/Applicant/Home/Feed/Offer/Info/JobSpecs/index.tsx
  src/pages/Applicant/Home/Feed/Offer/Info/component.tsx
  src/pages/Applicant/Home/Feed/Offer/Info/index.tsx
  src/pages/Applicant/Home/Feed/Offer/Info/styles.module.scss
  src/pages/Applicant/Home/Feed/Offer/component.tsx
  src/pages/Applicant/Home/Feed/Offer/github_logo.svg
  src/pages/Applicant/Home/Feed/Offer/index.tsx
  src/pages/Applicant/Home/Feed/Offer/styles.module.scss
  src/pages/Applicant/Home/Feed/component.tsx
  src/pages/Applicant/Home/Feed/index.tsx
  src/pages/Applicant/Home/Feed/styles.module.scss
  src/pages/Applicant/Home/index.tsx
  src/pages/Applicant/routes.tsx
  src/pages/Home/index.tsx
  src/styles/_variables.scss
  src/styles/mixins/_card.scss
  src/styles/mixins/_subtitle.scss
Labels: feature

#70 Fix offer list styles
  src/components/Button/styles.module.scss
  src/components/CompanyLogo/interface.tsx
  src/components/CompanyLogo/styles.module.scss
  src/components/ListItem/component.tsx
  src/components/ListItem/styles.module.scss
  src/components/NavBar/component.tsx
  src/components/Tag/styles.module.scss
  src/models/RoutesBuilder.ts
  src/pages/Applicant/Home/Feed/Offer/Info/JobSpecs/SpecItem/styles.module.scss
  src/pages/Applicant/Home/Feed/Offer/Info/JobSpecs/index.tsx
  src/pages/Applicant/Home/Feed/Offer/Info/component.tsx
  src/pages/Applicant/Home/Feed/Offer/Info/styles.module.scss
  src/pages/Applicant/Home/Feed/Offer/component.tsx
  src/pages/Applicant/Home/Feed/component.tsx
  src/pages/Applicant/Home/Feed/styles.module.scss
  src/pages/Applicant/OfferDetail/Detail/component.tsx
  src/pages/Applicant/OfferDetail/OfferInfo/styles.module.scss
  src/pages/Company/Profile/Detail/component.tsx
  src/styles/_variables.scss
Labels: feature

#73 Fetch Offers from back end and display the list
  src/graphql/queries/getOffers.graphql
  src/graphql/queries/index.ts
  src/pages/Applicant/Home/Feed/Offer/Info/component.tsx
  src/pages/Applicant/Home/Feed/Offer/github_logo.svg
  src/pages/Applicant/Home/Feed/constants.ts
  src/pages/Applicant/Home/Feed/container.tsx
  src/pages/Applicant/Home/Feed/github_logo.svg
  src/pages/Applicant/Home/Feed/meli_logo.svg
Labels: feature

#74 Agregado de comportamiento cuando se clickea en la card
  src/models/RoutesBuilder.ts
  src/pages/Applicant/Home/Feed/component.tsx
  src/pages/Applicant/Home/Feed/container.tsx
Labels: feature

#75 Feature/92 applicant form styles
  src/components/CareerSelector/styles.module.scss
  src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/styles.module.scss
  src/styles/mixins/_formSetMainColumn.scss
Labels: feature

#72 Add ability to submit to applicant edit form
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/Profile/Detail/container.tsx
Labels: feature

#76 Remove unused mutations
  src/graphql/mutations/deleteApplicantCapabilities.graphql
  src/graphql/mutations/deleteApplicantCareers.graphql
  src/graphql/mutations/index.ts
Labels: refactor

#79 Add password confirm to signup
  src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
  src/pages/Applicant/SignUp/component.tsx
  src/pages/Applicant/SignUp/container.tsx
  src/pages/Applicant/SignUp/interface.ts
  src/pages/Applicant/SignUp/translations.ts
Labels: feature

#78 Fix applicant detail styles
  src/components/Detail/ItemsDetail/styles.module.scss
  src/pages/Applicant/Profile/CapabilitiesDetail/component.tsx
Labels: fix

#77 Create user alongside applicant
  src/graphql/mutations/index.ts
  src/graphql/mutations/saveApplicant.graphql
  src/graphql/mutations/signUp.graphql
  src/pages/Applicant/SignUp/container.tsx
Labels: feature

#82 feat(92): Add new update and allow to update sections and links
  src/graphql/mutations/updateApplicant.graphql
  src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
Labels: feature

#80 Feature/114 login logout
  src/ApolloClient.ts
  src/components/NavBar/component.tsx
  src/components/NavBar/container.tsx
  src/components/NavBar/styles.module.scss
  src/graphql/mutations/index.ts
  src/graphql/mutations/login.graphql
  src/graphql/queries/index.ts
  src/graphql/queries/me.graphql
  src/interfaces/User/index.ts
  src/models/RoutesBuilder.ts
  src/models/Session.ts
  src/pages/Applicant/SignUp/container.tsx
  src/pages/LogIn/LogInForm/component.tsx
  src/pages/LogIn/LogInForm/container.tsx
  src/pages/LogIn/LogInForm/index.tsx
  src/pages/LogIn/LogInForm/interface.ts
  src/pages/LogIn/LogInForm/styles.module.scss
  src/pages/LogIn/index.tsx
  src/routes.tsx
  src/test/App.test.tsx
Labels: feature

#84 Fix 404 page styles
  public/images/brokenLink.svg
  public/images/notFound.jpg
  src/pages/NotFound/index.tsx
  src/pages/NotFound/styles.module.scss
  src/styles/base.scss
Labels: fix

#81 Fix desktop styles
  src/components/Description/component.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/styles.module.scss
  src/pages/Applicant/Home/Feed/Offer/Info/JobSpecs/index.tsx
  src/pages/Applicant/Home/Feed/Offer/Info/component.tsx
  src/pages/Applicant/Home/Feed/Offer/Info/styles.module.scss
  src/pages/Applicant/OfferDetail/Detail/component.tsx
  src/pages/Applicant/OfferDetail/Detail/styles.module.scss
  src/pages/Applicant/OfferDetail/OfferInfo/styles.module.scss
  src/styles/base.scss
Labels: fix

#83 Fix offer list styles
  src/components/CompanyLogo/styles.module.scss
  src/pages/Applicant/Home/Feed/Offer/Info/component.tsx
  src/pages/Applicant/Home/Feed/Offer/Info/styles.module.scss
  src/pages/Applicant/Home/Feed/Offer/component.tsx
  src/pages/Applicant/Home/Feed/Offer/styles.module.scss
  src/pages/Applicant/Home/Feed/styles.module.scss
Labels: fix

#85 Add saveJobApplication mutation
  src/graphql/mutations/index.ts
  src/graphql/mutations/saveJobApplication.graphql
  src/pages/Applicant/OfferDetail/Detail/component.tsx
  src/pages/Applicant/OfferDetail/Detail/container.tsx
Labels: feature

#86 Add hasApplied bollean to getOfferByUuid query to disable button
  src/graphql/queries/getOfferByUuid.graphql
  src/interfaces/Applicant/index.ts
  src/pages/Applicant/OfferDetail/Detail/component.tsx
  src/pages/Applicant/OfferDetail/Detail/container.tsx
Labels: feature

#87 Feature/114 login style
  src/App.tsx
  src/pages/LogIn/LogInForm/component.tsx
  src/pages/LogIn/LogInForm/container.tsx
  src/pages/LogIn/LogInForm/styles.module.scss
  src/pages/LogIn/fiubaLogo.png
  src/pages/LogIn/fiubaLogoMobile.png
  src/pages/LogIn/index.tsx
  src/pages/LogIn/styles.module.scss
Labels: feature

#89 Validate emtpy password
  src/pages/LogIn/LogInForm/component.tsx
  src/pages/LogIn/LogInForm/container.tsx
Labels: feature

#90 Fix linter issues
  package.json
  src/components/CapabilitiesSelector/container.tsx
  src/components/CareerSelector/container.tsx
  src/components/List/index.tsx
  src/components/NavBar/container.tsx
  src/components/TimeHumanizer/index.tsx
  src/pages/Applicant/Home/Feed/Offer/Info/JobSpecs/SpecItem/index.tsx
  src/pages/Applicant/Home/Feed/Offer/Info/JobSpecs/index.tsx
  src/pages/Applicant/Home/Feed/Offer/Info/component.tsx
  src/pages/Applicant/Home/Feed/Offer/component.tsx
  src/pages/Applicant/Home/Feed/component.tsx
  src/pages/Applicant/List/Applicants/component.tsx
  src/pages/Applicant/List/Applicants/container.tsx
  src/pages/Applicant/OfferDetail/Detail/component.tsx
  src/pages/Applicant/OfferDetail/Detail/container.tsx
  src/pages/Applicant/OfferDetail/OfferCareers/container.tsx
  src/pages/Applicant/OfferDetail/OfferSalary/container.tsx
  src/pages/Applicant/OfferDetail/OfferWorkload/container.tsx
  src/pages/Applicant/Profile/CareersDetail/container.tsx
  src/pages/Applicant/Profile/Detail/container.tsx
  src/pages/Applicant/Profile/Title/container.tsx
  src/pages/Applicant/SignUp/component.tsx
  src/pages/Applicant/SignUp/container.tsx
  src/pages/Applicant/routes.tsx
  src/pages/Company/Profile/Detail/interface.tsx
  src/pages/Company/Profile/Title/container.tsx
  src/pages/LogIn/LogInForm/container.tsx
  src/serviceWorker.ts
  yarn.lock
Labels: fix

#88 Translations hook
  package.json
  src/components/CapabilitiesSelector/container.tsx
  src/components/CareerSelector/container.tsx
  src/components/CareerSelector/interface.ts
  src/components/ListTitle/container.tsx
  src/components/NavBar/component.tsx
  src/components/NavBar/container.tsx
  src/components/NavBar/interface.ts
  src/graphql/queries/getTranslations.graphql
  src/models/hooks/translations.ts
  src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/interface.ts
  src/pages/Applicant/Home/Feed/component.tsx
  src/pages/Applicant/List/Applicants/component.tsx
  src/pages/Applicant/List/Applicants/container.tsx
  src/pages/Applicant/List/Applicants/interface.tsx
  src/pages/Applicant/OfferDetail/Detail/component.tsx
  src/pages/Applicant/OfferDetail/Detail/container.tsx
  src/pages/Applicant/OfferDetail/Detail/interface.ts
  src/pages/Applicant/OfferDetail/OfferCareers/container.tsx
  src/pages/Applicant/OfferDetail/OfferSalary/container.tsx
  src/pages/Applicant/OfferDetail/OfferSalary/interface.tsx
  src/pages/Applicant/OfferDetail/OfferWorkload/container.tsx
  src/pages/Applicant/OfferDetail/OfferWorkload/interface.tsx
  src/pages/Applicant/Profile/CareersDetail/component.tsx
  src/pages/Applicant/Profile/CareersDetail/container.tsx
  src/pages/Applicant/Profile/CareersDetail/interface.tsx
  src/pages/Applicant/Profile/Detail/component.tsx
  src/pages/Applicant/Profile/Detail/container.tsx
  src/pages/Applicant/Profile/Detail/interface.ts
  src/pages/Applicant/Profile/Title/container.tsx
  src/pages/Applicant/SignUp/component.tsx
  src/pages/Applicant/SignUp/container.tsx
  src/pages/Applicant/SignUp/interface.ts
  src/pages/Applicant/SignUp/translations.ts
  src/pages/Company/List/Companies/component.tsx
  src/pages/Company/List/Companies/container.tsx
  src/pages/Company/List/Companies/interface.tsx
  src/pages/Company/Profile/Title/container.tsx
  src/pages/LogIn/LogInForm/component.tsx
  src/pages/LogIn/LogInForm/container.tsx
  src/pages/LogIn/LogInForm/interface.ts
Labels: feature

#91 Add NumberInput component
  package.json
  src/components/CareerSelector/compontent.tsx
  src/components/NumberInput/index.tsx
  src/components/NumberInput/styles.module.scss
  src/models/FormikValidator.ts
  src/pages/Applicant/SignUp/component.tsx
  yarn.lock
Labels: refactor

#93 Add internal server error page
  public/images/internalServerError.svg
  src/components/ErrorPage/index.tsx
  src/components/ErrorPage/styles.module.scss
  src/components/Headline/component.tsx
  src/components/Headline/styles.module.scss
  src/pages/Applicant/OfferDetail/Detail/component.tsx
  src/pages/Applicant/OfferDetail/OfferCareers/component.tsx
  src/pages/Applicant/OfferDetail/OfferCareers/container.tsx
  src/pages/Applicant/OfferDetail/OfferCareers/interface.tsx
  src/pages/Applicant/Profile/Detail/component.tsx
  src/pages/Company/Profile/Detail/component.tsx
  src/pages/InternalServerError/index.tsx
  src/pages/LogIn/LogInForm/component.tsx
  src/pages/NotFound/index.tsx
  src/pages/NotFound/styles.module.scss
  src/routes.tsx
Labels: feature

#94 Add stylelint
  .stylelintrc.json
  package.json
  src/components/AddButton/styles.module.scss
  src/components/Button/index.tsx
  src/components/Button/interface.ts
  src/components/Button/styles.module.scss
  src/components/CareerSelector/styles.module.scss
  src/components/CompanyLogo/styles.module.scss
  src/components/Description/styles.module.scss
  src/components/Detail/DetailContactMe/styles.module.scss
  src/components/Detail/DetailMainContainer/styles.module.scss
  src/components/Detail/ItemsDetail/styles.module.scss
  src/components/Detail/ItemsDetailEditable/styles.module.scss
  src/components/ErrorPage/styles.module.scss
  src/components/FieldSet/styles.module.scss
  src/components/FormSection/styles.module.scss
  src/components/Headline/styles.module.scss
  src/components/Links/styles.module.scss
  src/components/List/styles.module.scss
  src/components/ListItem/styles.module.scss
  src/components/LoadingSpinner/styles.module.scss
  src/components/MainContent/styles.module.scss
  src/components/NavBar/styles.module.scss
  src/components/NumberInput/styles.module.scss
  src/components/RemoveButton/styles.module.scss
  src/components/SectionDetail/styles.module.scss
  src/components/Selector/BaseSelector/styles.module.scss
  src/components/Subtitle/styles.module.scss
  src/components/Tag/styles.module.scss
  src/components/TagSet/styles.module.scss
  src/components/TextInput/styles.module.scss
  src/components/TimeHumanizer/styles.module.scss
  src/components/Title/styles.module.scss
  src/pages/Applicant/EditableProfile/EditableDetail/styles.module.scss
  src/pages/Applicant/Home/Feed/Offer/Info/JobSpecs/SpecItem/styles.module.scss
  src/pages/Applicant/Home/Feed/Offer/Info/styles.module.scss
  src/pages/Applicant/Home/Feed/Offer/styles.module.scss
  src/pages/Applicant/Home/Feed/styles.module.scss
  src/pages/Applicant/List/Applicants/styles.module.scss
  src/pages/Applicant/OfferDetail/Detail/styles.module.scss
  src/pages/Applicant/OfferDetail/OfferCareers/styles.module.scss
  src/pages/Applicant/OfferDetail/OfferInfo/styles.module.scss
  src/pages/Applicant/OfferDetail/OfferInfoItem/styles.module.scss
  src/pages/Applicant/OfferDetail/OfferSalaryInfo/styles.module.scss
  src/pages/Applicant/OfferDetail/OfferWorkload/styles.module.scss
  src/pages/Applicant/Profile/Detail/styles.module.scss
  src/pages/Applicant/SignUp/styles.module.scss
  src/pages/Company/List/Companies/styles.module.scss
  src/pages/Company/Profile/Detail/styles.module.scss
  src/pages/LogIn/LogInForm/styles.module.scss
  src/pages/LogIn/styles.module.scss
  src/styles/_variables.scss
  src/styles/base.scss
  src/styles/mixins/_card.scss
  src/styles/mixins/_formSetMainColumn.scss
  src/styles/mixins/_subtitle.scss
  src/styles/mixins/_text.scss
  src/styles/mixins/_title.scss
  yarn.lock
Labels: feature

#96 Remove __typename from mutations
  src/models/hooks/index.ts
  src/models/hooks/useLogin.ts
  src/models/hooks/useMutation.ts
  src/models/hooks/useUpdateApplicant.ts
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/SignUp/container.tsx
  src/pages/LogIn/LogInForm/container.tsx
  src/test/models/hooks/useMutation.test.ts
Labels: fix
