Repository fiuba-laboral-v2/front-end, pull requests merged in 2020-06, with the labels that each got.

#146 Replace apollo client from apollo boost to apollo client
  package.json
  src/ApolloClient.ts
  src/components/NavBar/container.tsx
  src/graphql/mutations/index.ts
  src/graphql/mutations/logout.graphql
  src/models/Session.ts
  src/models/hooks/mutations/index.ts
  src/models/hooks/mutations/useLogout.ts
  src/pages/Applicant/SignUp/container.tsx
  src/pages/Company/SignUp/container.tsx
  src/pages/Public/LogIn/LogInForm/container.tsx
  yarn.lock
Labels: feature

#147 Add isAdmin boolean to currentUser query and interfaces to redirect t…
  src/graphql/queries/getCurrentUser.graphql
  src/interfaces/User/index.ts
  src/models/RoutesBuilder.ts
  src/models/hooks/queries/useCurrentUser.ts
  src/pages/Admin/Home/index.tsx
  src/pages/Admin/routes.tsx
  src/pages/Public/Home/index.tsx
  src/routes/AdminRoute.tsx
  src/routes/UserRoute.tsx
  src/routes/routes.tsx
Labels: feature

#149 Add admin to the context and remove isAdmin flag
  src/graphql/queries/getCurrentUser.graphql
  src/interfaces/User/index.ts
  src/models/hooks/queries/useCurrentUser.ts
  src/pages/Public/Home/index.tsx
  src/routes/AdminRoute.tsx
  src/routes/UserRoute.tsx
Labels: feature

#150 Feature/184 company status
  src/components/Link/index.tsx
  src/components/Link/styles.module.scss
  src/components/NavBar/component.tsx
  src/components/NavBar/container.tsx
  src/components/NavBar/interface.ts
  src/graphql/queries/getCompanyByUuid.graphql
  src/graphql/queries/getCurrentUser.graphql
  src/interfaces/ApprovalStatus/index.ts
  src/interfaces/Company/index.ts
  src/models/CurrentCompany.ts
  src/models/CurrentUser.ts
  src/models/Errors/PendingCompanyError.ts
  src/models/Errors/RejectedCompanyError.ts
  src/models/Errors/index.ts
  src/models/NavBarLinks/ApplicantNavBarLinks.ts
  src/models/NavBarLinks/CompanyNavBarLinks.ts
  src/models/NavBarLinks/Interfaces.ts
  src/models/NavBarLinks/NavBarLinks.ts
  src/models/NavBarLinks/getTooltipMessage.ts
  src/models/NavBarLinks/index.ts
  src/models/Permissions/CompanyPermissions.ts
  src/models/Permissions/Permissions.ts
  src/models/Permissions/index.ts
  src/models/Router/CompanyRouter.ts
  src/models/Router/Router.ts
  src/models/Router/index.ts
  src/models/hooks/queries/useCurrentUser.ts
  src/pages/Public/Home/index.tsx
  src/routes/UserRoute.tsx
  src/test/models/CurrentCompany.test.ts
  src/test/models/CurrentUser.test.ts
  src/test/models/NavBarLinks/NavBarLinks.test.ts
  src/test/models/Permissions/Permissions.test.ts
  src/test/models/Router/Router.test.ts
Labels: feature

#151 Use query DocumentNode in useOfferByUuid hook to get offer
  src/models/hooks/queries/useOfferByUuid.ts
Labels: feature

#152 Make first letter upercase in TimeHumanizer
  src/components/TimeHumanizer/index.tsx
Labels: fix

#157 Feature/189 select task
  src/pages/Admin/Home/Dashboard/AdminTaskDetail/CompanyDetailContent/component.tsx
  src/pages/Admin/Home/Dashboard/AdminTaskDetail/CompanyDetailContent/container.tsx
  src/pages/Admin/Home/Dashboard/AdminTaskDetail/CompanyDetailContent/index.ts
  src/pages/Admin/Home/Dashboard/AdminTaskDetail/component.tsx
  src/pages/Admin/Home/Dashboard/AdminTaskList/ApprovableEntity/component.tsx
  src/pages/Admin/Home/Dashboard/AdminTaskList/ListBody/component.tsx
  src/pages/Admin/Home/Dashboard/AdminTaskList/ListBody/container.tsx
  src/pages/Admin/Home/Dashboard/AdminTaskList/component.tsx
  src/pages/Admin/Home/Dashboard/component.tsx
Labels: feature

#158 Add buttons to update company status in admin
  src/graphql/mutations/index.ts
  src/graphql/mutations/updateCompanyApprovalStatus.graphql
  src/models/hooks/mutations/index.ts
  src/models/hooks/mutations/useUpdateCompanyApprovalStatus.ts
  src/pages/Admin/Home/Dashboard/AdminTaskDetail/CompanyDetailInfo/component.tsx
  src/pages/Admin/Home/Dashboard/AdminTaskDetail/CompanyDetailInfo/container.tsx
  src/pages/Admin/Home/Dashboard/AdminTaskDetail/CompanyDetailInfo/index.ts
  src/pages/Admin/Home/Dashboard/AdminTaskDetail/component.tsx
Labels: feature

#159 Feature/200 admin home page translations
  src/components/ApplicantDetail/component.tsx
  src/components/CompanyDetail/index.tsx
  src/components/Description/component.tsx
  src/pages/Admin/Home/Dashboard/AdminTaskDetail/EmptyDetailContent/component.tsx
  src/pages/Admin/Home/Dashboard/AdminTaskDetail/EmptyDetailContent/container.tsx
  src/pages/Admin/Home/Dashboard/AdminTaskDetail/EmptyDetailContent/index.ts
  src/pages/Admin/Home/Dashboard/AdminTaskDetail/EmptyDetailContent/interfaces.ts
  src/pages/Admin/Home/Dashboard/AdminTaskDetail/EmptyDetailContent/styles.module.scss
  src/pages/Admin/Home/Dashboard/AdminTaskDetail/component.tsx
  src/pages/Admin/Home/Dashboard/Menu/component.tsx
  src/pages/Admin/Home/Dashboard/Menu/container.tsx
  src/pages/Admin/Home/Dashboard/Menu/index.tsx
  src/pages/Admin/Home/Dashboard/Menu/interfaces.ts
Labels: feature

#160 Feature/201 update cache after moderation
  src/models/hooks/mutations/useUpdateCompanyApprovalStatus.ts
  src/models/hooks/queries/usePendingEntities.ts
  src/pages/Admin/Home/Dashboard/AdminTaskDetail/CompanyDetailInfo/container.tsx
Labels: feature

#161 Add pending tasks counter; Close task detail on status update
  src/pages/Admin/Home/Dashboard/AdminTaskDetail/index.tsx
  src/pages/Admin/Home/Dashboard/AdminTaskList/ListBody/container.tsx
  src/pages/Admin/Home/Dashboard/AdminTaskList/ListBody/index.ts
  src/pages/Admin/Home/Dashboard/AdminTaskList/component.tsx
  src/pages/Admin/Home/Dashboard/AdminTaskList/index.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/CompanyDetailContent/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/CompanyDetailContent/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/CompanyDetailContent/index.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/CompanyDetailInfo/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/CompanyDetailInfo/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/CompanyDetailInfo/index.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/EmptyDetailContent/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/EmptyDetailContent/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/EmptyDetailContent/index.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/EmptyDetailContent/interfaces.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/EmptyDetailContent/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskDetail/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/index.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskList/ApprovableCompany/component.tsx
  src/pages/Admin/Home/Dashboard/TaskList/ApprovableCompany/index.ts
  src/pages/Admin/Home/Dashboard/TaskList/ApprovableEntity/component.tsx
  src/pages/Admin/Home/Dashboard/TaskList/ApprovableEntity/index.ts
  src/pages/Admin/Home/Dashboard/TaskList/ListBody/component.tsx
  src/pages/Admin/Home/Dashboard/TaskList/ListBody/index.ts
  src/pages/Admin/Home/Dashboard/TaskList/ListBody/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskList/ListInfo/component.tsx
  src/pages/Admin/Home/Dashboard/TaskList/ListInfo/index.ts
  src/pages/Admin/Home/Dashboard/TaskList/ListInfo/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskList/component.tsx
  src/pages/Admin/Home/Dashboard/TaskList/container.tsx
  src/pages/Admin/Home/Dashboard/TaskList/index.tsx
  src/pages/Admin/Home/Dashboard/TaskList/interface.ts
  src/pages/Admin/Home/Dashboard/TaskList/styles.module.scss
  src/pages/Admin/Home/Dashboard/component.tsx
Labels: feature

#163 Fix scrolling in admin dashboard
  src/components/ClickableCard/component.tsx
  src/components/ClickableCard/styles.module.scss
  src/components/Window/component.tsx
  src/pages/Admin/Home/Dashboard/Menu/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskDetail/EmptyDetail/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/EmptyDetail/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/EmptyDetail/index.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/EmptyDetail/interfaces.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/EmptyDetail/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskDetail/EmptyDetailContent/index.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/EmptyDetailContent/interfaces.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskList/ListBody/component.tsx
  src/pages/Admin/Home/Dashboard/TaskList/ListBody/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskList/ListInfo/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskList/component.tsx
  src/pages/Admin/Home/Dashboard/TaskList/container.tsx
  src/pages/Admin/Home/Dashboard/TaskList/interface.ts
  src/pages/Admin/Home/Dashboard/TaskList/styles.module.scss
  src/pages/Admin/Home/Dashboard/component.tsx
  src/pages/Admin/Home/Dashboard/styles.module.scss
  src/styles/_variables.scss
Labels: feature

#164 Add company icon to company tasks in admin homepage
  src/pages/Admin/Home/Dashboard/CompanyIcon/component.tsx
  src/pages/Admin/Home/Dashboard/CompanyIcon/styles.module.scss
  src/pages/Admin/Home/Dashboard/Menu/component.tsx
  src/pages/Admin/Home/Dashboard/Menu/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskList/ApprovableCompany/component.tsx
  src/pages/Admin/Home/Dashboard/TaskList/ApprovableCompany/index.ts
  src/pages/Admin/Home/Dashboard/TaskList/ApprovableEntity/component.tsx
  src/pages/Admin/Home/Dashboard/TaskList/ApprovableEntity/styles.module.scss
Labels: feature

#166 Rename sizes variables
  .stylelintrc.json
  src/components/AddButton/styles.module.scss
  src/components/ApplicantDetail/styles.module.scss
  src/components/CareerSelector/styles.module.scss
  src/components/CompanyDetail/styles.module.scss
  src/components/CompanyLogo/styles.module.scss
  src/components/Description/styles.module.scss
  src/components/Detail/DetailContactMe/styles.module.scss
  src/components/EditOffer/styles.module.scss
  src/components/ErrorPage/styles.module.scss
  src/components/FieldSet/styles.module.scss
  src/components/FormFooter/styles.module.scss
  src/components/FormSection/styles.module.scss
  src/components/Header/styles.module.scss
  src/components/Headline/styles.module.scss
  src/components/Links/styles.module.scss
  src/components/MainContent/styles.module.scss
  src/components/NavBar/styles.module.scss
  src/components/NumberInput/styles.module.scss
  src/components/OfferCareers/styles.module.scss
  src/components/OfferDetail/styles.module.scss
  src/components/OfferInfo/styles.module.scss
  src/components/OfferInfoItem/styles.module.scss
  src/components/OfferSalaryInfo/styles.module.scss
  src/components/OfferWorkload/styles.module.scss
  src/components/SectionDetail/styles.module.scss
  src/components/Subtitle/styles.module.scss
  src/components/Tag/styles.module.scss
  src/components/TextInput/styles.module.scss
  src/pages/Admin/Home/Dashboard/Menu/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskDetail/EmptyDetail/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskList/ApprovableEntity/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskList/ListBody/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskList/ListInfo/styles.module.scss
  src/pages/Applicant/Companies/styles.module.scss
  src/pages/Applicant/EditableProfile/EditableDetail/styles.module.scss
  src/pages/Applicant/Home/Feed/Offer/Info/JobSpecs/SpecItem/styles.module.scss
  src/pages/Applicant/Home/Feed/Offer/Info/styles.module.scss
  src/pages/Applicant/Home/Feed/styles.module.scss
  src/pages/Applicant/List/Applicants/styles.module.scss
  src/pages/Applicant/OfferDetail/styles.module.scss
  src/pages/Applicant/SignUp/styles.module.scss
  src/pages/Company/EditableProfile/styles.module.scss
  src/pages/Company/MyJobApplications/JobApplication/styles.module.scss
  src/pages/Company/MyJobApplications/styles.module.scss
  src/pages/Company/SignUp/styles.module.scss
  src/pages/Public/InternalServerError/styles.module.scss
  src/pages/Public/LogIn/LogInForm/styles.module.scss
  src/pages/Public/Register/styles.module.scss
  src/styles/_variables.scss
  src/styles/base.scss
  src/styles/mixins/_formSetMainColumn.scss
  src/styles/mixins/_subtitle.scss
  src/styles/mixins/_text.scss
  src/styles/mixins/_title.scss
Labels: refactor
