Repository fiuba-laboral-v2/front-end, pull requests merged in 2020-10, with the labels that each got.

#289 adding offers list page in navbar
  src/models/NavBarLinks/AdminNavBarLinks.ts
  src/models/RoutesBuilder.ts
  src/pages/Admin/Offers/container.tsx
  src/pages/Admin/Offers/index.ts
  src/pages/Admin/routes.tsx
  src/test/models/NavBarLinks/NavBarLinks.test.ts
Labels: feature

#290 offer list page
  src/components/CareerList/index.tsx
  src/components/CareerList/styles.module.scss
  src/components/OfferCareers/component.tsx
  src/graphql/queries/getOffers.graphql
  src/pages/Admin/Offers/Columns/constants.ts
  src/pages/Admin/Offers/Columns/index.tsx
  src/pages/Admin/Offers/ListContentItem/index.tsx
  src/pages/Admin/Offers/ListContentItem/styles.module.scss
  src/pages/Admin/Offers/ListHeader/Item/index.tsx
  src/pages/Admin/Offers/ListHeader/Item/styles.module.scss
  src/pages/Admin/Offers/ListHeader/component.tsx
  src/pages/Admin/Offers/ListHeader/container.tsx
  src/pages/Admin/Offers/ListHeader/index.ts
  src/pages/Admin/Offers/container.tsx
  src/pages/Admin/Offers/styles.module.scss
  src/pages/Admin/components/ListPageContainer/interfaces.ts
Labels: feature

#291 Refactor/295 applicant signup form
  src/components/FormSection/styles.module.scss
  src/pages/Applicant/SignUp/ApplicantCredentialsFields/component.tsx
  src/pages/Applicant/SignUp/ApplicantCredentialsFields/container.tsx
  src/pages/Applicant/SignUp/ApplicantCredentialsFields/index.tsx
  src/pages/Applicant/SignUp/ApplicantCredentialsFields/interfaces.ts
  src/pages/Applicant/SignUp/CareersSelectorForm/component.tsx
  src/pages/Applicant/SignUp/CareersSelectorForm/container.tsx
  src/pages/Applicant/SignUp/CareersSelectorForm/index.ts
  src/pages/Applicant/SignUp/CareersSelectorForm/interfaces.ts
  src/pages/Applicant/SignUp/CareersSelectorForm/styles.module.scss
  src/pages/Applicant/SignUp/FiubaCredentialsForm/component.tsx
  src/pages/Applicant/SignUp/FiubaCredentialsForm/container.tsx
  src/pages/Applicant/SignUp/FiubaCredentialsForm/index.ts
  src/pages/Applicant/SignUp/FiubaCredentialsForm/interfaces.ts
  src/pages/Applicant/SignUp/FiubaCredentialsForm/styles.module.scss
  src/pages/Applicant/SignUp/PersonalInformationForm/component.tsx
  src/pages/Applicant/SignUp/PersonalInformationForm/container.tsx
  src/pages/Applicant/SignUp/PersonalInformationForm/index.ts
  src/pages/Applicant/SignUp/PersonalInformationForm/interfaces.ts
  src/pages/Applicant/SignUp/PersonalInformationForm/styles.module.scss
  src/pages/Applicant/SignUp/component.tsx
  src/pages/Applicant/SignUp/interface.ts
  src/pages/Applicant/SignUp/styles.module.scss
Labels: refactor

#295 Refactor/296 knowledge sections
  src/cache/typePolicies/index.ts
  src/components/ApplicantDetail/component.tsx
  src/components/ApplicantDetail/container.tsx
  src/graphql/mutations/updateCurrentApplicant.graphql
  src/graphql/queries/getApplicant.graphql
  src/graphql/queries/getMyApplicantProfile.graphql
  src/interfaces/Applicant/index.ts
  src/models/hooks/mutations/useUpdateCurrentApplicant.ts
  src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/EditableProfile/SectionsFormSection/component.tsx
  src/test/models/MutationArguments/Applicant/updateCurrentApplicantArguments.test.ts
Labels: refactor

#298 Fix: Add experienceSection to the mutation params
  src/graphql/mutations/updateCurrentApplicant.graphql
Labels: fix

#300 Remove unnecesary component
  src/components/FieldSet/index.tsx
  src/components/FieldSet/styles.module.scss
  src/components/FormFooter/index.tsx
  src/components/FormSection/index.tsx
  src/components/FormSection/styles.module.scss
Labels: fix, refactor

#301 Add FormSection component
  src/components/CapabilitiesSelector/compontent.tsx
  src/components/CapabilitiesSelector/container.tsx
  src/components/CapabilitiesSelector/interface.ts
  src/components/FormSection/index.tsx
  src/components/FormSection/styles.module.scss
  src/components/SearchSelector/MultipleSearchSelector/index.tsx
  src/components/SearchSelector/MultipleSearchSelector/styles.module.scss
  src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/styles.module.scss
  src/pages/Applicant/EditableProfile/PersonalInformationFormSection/component.tsx
  src/pages/Applicant/EditableProfile/PersonalInformationFormSection/styles.module.scss
  src/pages/Applicant/EditableProfile/SkillsAndLanguagesFormSection/component.tsx
  src/pages/Applicant/EditableProfile/SkillsAndLanguagesFormSection/styles.module.scss
  src/pages/Applicant/SignUp/FiubaCredentialsFormSection/component.tsx
  src/pages/Applicant/SignUp/FiubaCredentialsFormSection/styles.module.scss
  src/pages/Applicant/SignUp/PersonalInformationFormSection/component.tsx
  src/pages/Applicant/SignUp/PersonalInformationFormSection/styles.module.scss
  src/pages/Company/SignUp/CompanyDataFormSection/component.tsx
  src/pages/Company/SignUp/CompanyDataFormSection/styles.module.scss
  src/pages/Company/SignUp/ContactInformationFormSection/component.tsx
  src/pages/Company/SignUp/UserDataFormSection/component.tsx
  src/pages/Company/SignUp/UserDataFormSection/styles.module.scss
  src/styles/mixins/_formSectionTitle.scss
Labels: refactor

#303 Refactor/298 edit company profile
  public/images/imageUpload.png
  src/components/CompanyDetail/index.tsx
  src/components/CompanyFields/component.tsx
  src/components/CompanyFields/container.tsx
  src/components/CompanyFields/index.ts
  src/components/CompanyFields/interface.ts
  src/components/CompanyLogo/component.tsx
  src/components/CompanyLogo/styles.module.scss
  src/components/CompanyLogo/styles.ts
  src/components/CompanyLogoInput/component.tsx
  src/components/CompanyLogoInput/container.tsx
  src/components/CompanyLogoInput/index.ts
  src/components/CompanyLogoInput/index.tsx
  src/components/CompanyLogoInput/interfaces.ts
  src/components/CompanyLogoInput/styles.module.scss
  src/components/ContactInformationFormSection/component.tsx
  src/components/ContactInformationFormSection/container.tsx
  src/components/ContactInformationFormSection/index.ts
  src/components/ContactInformationFormSection/interfaces.ts
  src/components/Feed/Offer/Info/component.tsx
  src/components/Feed/Offer/component.tsx
  src/components/Icons/ApplicantIcon/index.tsx
  src/components/Icons/ApplicantIcon/styles.module.scss
  src/components/Icons/CompanyIcon/index.tsx
  src/components/Icons/CompanyIcon/styles.module.scss
  src/components/Icons/JobApplicationIcon/index.tsx
  src/components/Icons/JobApplicationIcon/styles.module.scss
  src/components/Icons/OfferIcon/index.tsx
  src/components/Icons/OfferIcon/styles.module.scss
  src/components/OfferDetail/component.tsx
  src/pages/Admin/Home/Dashboard/Menu/TypeFilter/component.tsx
  src/pages/Admin/Home/Dashboard/TaskList/AdminTask/container.tsx
  src/pages/Applicant/Companies/component.tsx
  src/pages/Company/EditableProfile/CompanyDataFormSection/component.tsx
  src/pages/Company/EditableProfile/CompanyDataFormSection/container.tsx
  src/pages/Company/EditableProfile/CompanyDataFormSection/index.ts
  src/pages/Company/EditableProfile/CompanyDataFormSection/interfaces.ts
  src/pages/Company/EditableProfile/CompanyDataFormSection/styles.module.scss
  src/pages/Company/EditableProfile/component.tsx
  src/pages/Company/EditableProfile/styles.module.scss
  src/pages/Company/SignUp/component.tsx
  src/styles/mixins/_logoSize.scss
Labels: refactor

#311 Feature/297 acceptance criteria
  src/components/AcceptanceCriteria/index.tsx
  src/components/AcceptanceCriteria/styles.module.scss
  src/pages/Company/SignUp/component.tsx
  src/pages/Company/SignUp/container.tsx
  src/pages/Company/SignUp/styles.module.scss
  src/styles/base.scss
Labels: feature

#312 Feature/298 acceptance criteria
  src/components/Form/index.tsx
  src/components/Form/styles.module.scss
  src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/interface.ts
  src/pages/Applicant/EditableProfile/EditableDetail/styles.module.scss
  src/pages/Applicant/EditableProfile/index.tsx
  src/pages/Applicant/OfferDetail/component.tsx
  src/pages/Applicant/SignUp/component.tsx
  src/pages/Applicant/SignUp/container.tsx
  src/pages/Applicant/SignUp/index.tsx
  src/pages/Applicant/SignUp/styles.module.scss
  src/pages/Company/EditableProfile/component.tsx
  src/pages/Company/EditableProfile/container.tsx
  src/pages/Company/EditableProfile/styles.module.scss
  src/pages/Company/SignUp/component.tsx
  src/pages/Company/SignUp/styles.module.scss
Labels: feature

#319 Add careers argument to the editOffer mutation file
  src/cache/typePolicies/index.ts
  src/graphql/mutations/editOffer.graphql
  src/pages/Company/EditOffer/container.tsx
Labels: feature

#328 Feature/383 mandatory fields
  src/components/ApplicantCareerSelector/component.tsx
  src/components/ApplicantCareerSelector/interface.ts
  src/components/CareerSelector/component.tsx
  src/components/CareerSelector/interfaces.ts
  src/components/EditOffer/RecipientsFormSection/component.tsx
  src/components/Fields/EmailField/index.tsx
  src/components/Fields/Field/index.tsx
  src/components/Fields/NameField/index.tsx
  src/components/Fields/SalaryField/index.tsx
  src/components/NumberInput/PositiveNumberInput/index.tsx
  src/components/NumberInput/index.tsx
  src/components/NumberInput/interfaces.ts
  src/components/SearchSelector/BaseSearchSelector/index.tsx
  src/components/SectionsFormSection/component.tsx
  src/components/TargetApplicantTypeSelector/component.tsx
  src/components/TargetApplicantTypeSelector/interfaces.ts
  src/components/TextInput/index.tsx
  src/materialUITheme.ts
  src/pages/Applicant/EditableProfile/LinksFormSection/component.tsx
  src/pages/Applicant/EditableProfile/PersonalInformationFormSection/component.tsx
  src/pages/Applicant/SignUp/FiubaCredentialsFormSection/component.tsx
  src/pages/Applicant/SignUp/PersonalInformationFormSection/component.tsx
  src/pages/Company/EditableProfile/CompanyDataFormSection/component.tsx
  src/pages/Company/SignUp/CompanyDataFormSection/component.tsx
  src/pages/Company/SignUp/UserDataFormSection/component.tsx
Labels: feature

#332 Feature/401 offer carrers prescense validation
  src/components/CareerSelector/component.tsx
  src/components/SearchSelector/MultipleSearchSelector/index.tsx
  src/models/FormikValidator.ts
  src/test/models/FormikValidator.test.ts
Labels: feature
