Repository fiuba-laboral-v2/front-end, pull requests merged in 2020-08, with the labels that each got.

#207 Add mandatory dni to applicant sign up and remove passwordConfirm
  package.json
  src/components/CompanyFields/component.tsx
  src/components/Fields/DniField/index.tsx
  src/components/Fields/EmailField/index.tsx
  src/components/Fields/NameField/index.tsx
  src/components/Fields/PasswordField/index.tsx
  src/components/Fields/index.tsx
  src/components/Fields/interfaces.ts
  src/components/UserFields/component.tsx
  src/components/UserFields/container.tsx
  src/components/UserFields/index.tsx
  src/components/UserInput/index.tsx
  src/interfaces/User/index.ts
  src/models/hooks/mutations/useSaveApplicant.ts
  src/pages/Applicant/SignUp/ApplicantCredentialsFields/component.tsx
  src/pages/Applicant/SignUp/ApplicantCredentialsFields/container.tsx
  src/pages/Applicant/SignUp/ApplicantCredentialsFields/index.tsx
  src/pages/Applicant/SignUp/component.tsx
  src/pages/Applicant/SignUp/container.tsx
  src/pages/Applicant/SignUp/interface.ts
  src/pages/Company/SignUp/CompanyCredentialsFields/component.tsx
  src/pages/Company/SignUp/CompanyCredentialsFields/container.tsx
  src/pages/Company/SignUp/CompanyCredentialsFields/index.tsx
  src/pages/Company/SignUp/component.tsx
  src/pages/Company/SignUp/interface.ts
  yarn.lock
Labels: feature

#206 Add pagination to admin homescreen
  package.json
  src/ApolloClient.ts
  src/App.tsx
  src/cache/InMemoryCache.ts
  src/cache/possibleTypes.ts
  src/cache/typePolicies/index.ts
  src/cache/typePolicies/queries/getOffers.ts
  src/cache/typePolicies/queries/index.ts
  src/components/ApplicantDetail/container.tsx
  src/components/CapabilitiesSelector/container.tsx
  src/components/CareerSelector/container.tsx
  src/components/List/component.tsx
  src/components/List/interface.ts
  src/components/NavBar/container.tsx
  src/config/codegen.yml
  src/config/fragmentTypes.json
  src/graphql/queries/getAdminTasks.graphql
  src/graphql/queries/getOffers.graphql
  src/interfaces/AdminTask/index.ts
  src/models/handleError.ts
  src/models/hooks/mutations/useLogin.ts
  src/models/hooks/mutations/useUpdateAdminTaskStatus.ts
  src/models/hooks/mutations/useUpdateAdminTaskStatusMutation.ts
  src/models/hooks/queries/index.ts
  src/models/hooks/queries/useAdminTasks.ts
  src/models/hooks/queries/useGetAdminTasks.ts
  src/models/hooks/queries/useOffers.ts
  src/models/hooks/useMutation.ts
  src/models/hooks/useQuery.ts
  src/pages/Admin/Home/Dashboard/TaskList/ListBody/component.tsx
  src/pages/Admin/Home/Dashboard/TaskList/component.tsx
  src/pages/Admin/Home/Dashboard/TaskList/container.tsx
  src/pages/Admin/Home/Dashboard/TaskList/interface.ts
  src/pages/Admin/Home/Dashboard/component.tsx
  src/pages/Admin/Home/Dashboard/container.tsx
  src/pages/Applicant/Home/Feed/container.tsx
  src/pages/Applicant/List/Applicants/container.tsx
  src/pages/Applicant/OfferDetail/container.tsx
  src/test/models/handleError.test.ts
  yarn.lock
Labels: feature

#209 Migrate dni to string
  package.json
  src/components/Fields/DniField/index.tsx
  src/interfaces/User/index.ts
  src/pages/Applicant/SignUp/component.tsx
  yarn.lock
Labels: refactor

#210 Add FiubaUsersServiceFetchError as error to be handle
  src/models/errorHandlers/FiubaServiceFetchErrorHandler.ts
  src/models/handleError.ts
  src/pages/Applicant/SignUp/container.tsx
Labels: feature

#211 Add isGraduate to ApplicantCareer interfaces and graphql files
  src/graphql/mutations/saveApplicant.graphql
  src/graphql/mutations/updateCurrentApplicant.graphql
  src/graphql/queries/getApplicant.graphql
  src/graphql/queries/getMyApplicantProfile.graphql
  src/interfaces/Applicant/index.ts
  src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/SignUp/component.tsx
Labels: feature

#212 Refactor/applicant career graphql type
  src/components/CareerSelector/interface.ts
  src/components/CareersDetail/component.tsx
  src/components/CareersDetail/interface.tsx
  src/components/OfferCareers/component.tsx
  src/graphql/mutations/saveApplicant.graphql
  src/graphql/mutations/updateCurrentApplicant.graphql
  src/graphql/queries/getApplicant.graphql
  src/graphql/queries/getMyApplicantProfile.graphql
  src/interfaces/Applicant/index.ts
  src/interfaces/Career/index.ts
  src/interfaces/Offer/index.tsx
  src/models/hooks/mutations/useSaveApplicant.ts
  src/models/hooks/mutations/useUpdateCurrentApplicant.ts
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/interface.ts
Labels: refactor

#214 Omit careerCode from ApplicantCareer interface in the IApplicant care…
  src/interfaces/Applicant/index.ts
Labels: refactor

#216 Feature/206 applicant career progress
  src/components/CareerSelector/compontent.tsx
  src/components/CareerSelector/container.tsx
  src/components/CareerSelector/interface.ts
  src/components/CareersDetail/component.tsx
  src/components/CareersDetail/interface.tsx
  src/graphql/mutations/saveApplicant.graphql
  src/graphql/mutations/updateCurrentApplicant.graphql
  src/graphql/queries/getApplicant.graphql
  src/graphql/queries/getMyApplicantProfile.graphql
  src/interfaces/Applicant/index.ts
  src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/SignUp/component.tsx
  src/pages/Applicant/SignUp/container.tsx
Labels: feature

#218 Feature/206 careers input
  src/components/CareerSelector/compontent.tsx
  src/components/CareerSelector/container.tsx
  src/components/CareerSelector/interface.ts
  src/components/CareerSelector/styles.module.scss
  src/components/CheckboxInput/index.tsx
  src/components/CheckboxInput/styles.module.scss
  src/components/Fields/DniField/index.tsx
  src/components/Fields/EmailField/index.tsx
  src/components/Fields/NameField/index.tsx
  src/components/Fields/PasswordField/index.tsx
  src/components/Fields/interfaces.ts
  src/components/NumberInput/PositiveNumberInput/index.tsx
  src/components/NumberInput/index.tsx
  src/components/NumberInput/interfaces.ts
  src/components/TextInput/index.tsx
  src/components/UserEditFields/component.tsx
  src/components/UserEditFields/container.tsx
  src/components/UserEditFields/index.ts
  src/components/UserEditFields/interfaces.ts
  src/components/UserEditFields/styles.module.scss
  src/components/UserFields/component.tsx
  src/components/UserFields/container.tsx
  src/components/UserFields/interfaces.ts
  src/graphql/queries/getCareers.graphql
  src/models/MutationArguments/Applicant/applicantCareersInputArguments.ts
  src/models/MutationArguments/Applicant/index.ts
  src/models/MutationArguments/Applicant/saveApplicantArguments.ts
  src/models/MutationArguments/Applicant/updateCurrentApplicantArguments.ts
  src/models/MutationArguments/index.ts
  src/models/hooks/mutations/useUpdateCurrentApplicant.ts
  src/models/hooks/queries/index.ts
  src/models/hooks/queries/useCareers.ts
  src/pages/Applicant/EditableProfile/EditableDetail/component.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/container.tsx
  src/pages/Applicant/EditableProfile/EditableDetail/interface.ts
  src/pages/Applicant/EditableProfile/EditableDetail/styles.module.scss
  src/pages/Applicant/SignUp/ApplicantCredentialsFields/component.tsx
  src/pages/Applicant/SignUp/ApplicantCredentialsFields/container.tsx
  src/pages/Applicant/SignUp/ApplicantCredentialsFields/interfaces.ts
  src/pages/Applicant/SignUp/container.tsx
  src/pages/Applicant/SignUp/interface.ts
  src/styles/mixins/_formSetMainColumn.scss
  src/test/models/MutationArguments/Applicant/applicantCareersInputArguments.test.ts
  src/test/models/MutationArguments/Applicant/saveApplicantArguments.test.ts
  src/test/models/MutationArguments/Applicant/updateCurrentApplicantArguments.test.ts
Labels: feature

#219 Add currentCarrerYear and number of approved subjects to careers deta…
  src/components/CareersDetail/GraduateCareerDetail/index.tsx
  src/components/CareersDetail/StudentCareerDetail/index.tsx
  src/components/CareersDetail/component.tsx
  src/components/CareersDetail/container.tsx
  src/components/CareersDetail/interface.tsx
  src/components/CareersDetail/styles.module.scss
  src/components/CheckboxInput/index.tsx
  src/components/Detail/ItemsDetail/component.tsx
  src/components/Detail/ItemsDetail/index.tsx
  src/components/Detail/ItemsDetail/interface.tsx
  src/components/Detail/ItemsDetailEditable/component.tsx
  src/components/Detail/ItemsDetailEditable/container.tsx
  src/components/Detail/ItemsDetailEditable/index.tsx
  src/components/Detail/ItemsDetailEditable/interface.tsx
  src/components/Detail/ItemsDetailEditable/styles.module.scss
Labels: feature

#220 Remove credits from career type
  src/graphql/mutations/saveApplicant.graphql
  src/graphql/mutations/updateCurrentApplicant.graphql
  src/graphql/queries/getApplicant.graphql
  src/graphql/queries/getCareers.graphql
  src/graphql/queries/getMyApplicantProfile.graphql
  src/graphql/queries/getMyOffers.graphql
  src/graphql/queries/getOfferByUuid.graphql
  src/interfaces/Career/index.ts
Labels: feature

#222 Feature/238 target applicant type
  src/components/EditOffer/index.tsx
  src/components/TargetApplicantTypeSelector/component.tsx
  src/components/TargetApplicantTypeSelector/container.tsx
  src/components/TargetApplicantTypeSelector/index.tsx
  src/components/TargetApplicantTypeSelector/interfaces.ts
  src/graphql/mutations/createOffer.graphql
  src/graphql/queries/getCompanyOfferByUuid.graphql
  src/graphql/queries/getMyOffers.graphql
  src/interfaces/Offer/index.tsx
  src/models/hooks/mutations/useCreateOffer.ts
  src/models/hooks/mutations/useEditOffer.ts
  src/pages/Company/CreateOffer/container.tsx
  src/pages/Company/EditOffer/container.tsx
Labels: feature

#223 Update cache after editOffer mutation
  src/graphql/mutations/editOffer.graphql
  src/pages/Company/EditOffer/container.tsx
Labels: feature

#224 Add OfferTargetApplicantType component
  src/components/OfferInfo/component.tsx
  src/components/OfferInfo/styles.module.scss
  src/components/OfferTargetApplicantType/component.tsx
  src/components/OfferTargetApplicantType/container.tsx
  src/components/OfferTargetApplicantType/index.ts
  src/components/OfferTargetApplicantType/interfaces.ts
  src/components/OfferWorkload/component.tsx
  src/graphql/queries/getOfferByUuid.graphql
Labels: feature

#226 Add translation to targetApplicantTypeSelector group
  src/components/TargetApplicantTypeSelector/component.tsx
  src/components/TargetApplicantTypeSelector/container.tsx
  src/components/TargetApplicantTypeSelector/interfaces.ts
  src/interfaces/Offer/index.tsx
Labels: refactor

#229 Feature/265 job application admin task
  src/graphql/queries/getAdminTasks.graphql
  src/graphql/typenames/index.ts
  src/interfaces/AdminTask/index.ts
  src/pages/Admin/Home/Dashboard/Icons/JobApplicationIcon/index.tsx
  src/pages/Admin/Home/Dashboard/Icons/JobApplicationIcon/styles.module.scss
  src/pages/Admin/Home/Dashboard/Menu/Tab/index.tsx
  src/pages/Admin/Home/Dashboard/Menu/Tab/styles.module.scss
  src/pages/Admin/Home/Dashboard/Menu/TypeFilter/component.tsx
  src/pages/Admin/Home/Dashboard/Menu/TypeFilter/interfaces.ts
  src/pages/Admin/Home/Dashboard/TaskList/AdminTask/container.tsx
  src/pages/Admin/Home/Dashboard/container.tsx
  src/styles/_variables.scss
Labels: feature

#230 Fix/254 form autocomplete
  src/components/Fields/DniField/index.tsx
  src/components/Fields/EmailField/index.tsx
  src/components/Fields/PasswordField/index.tsx
  src/pages/Applicant/SignUp/ApplicantCredentialsFields/component.tsx
  src/pages/Company/SignUp/CompanyCredentialsFields/component.tsx
  src/pages/Public/LogIn/LogInForm/component.tsx
Labels: fix

#234 Feature/266 job appliation detail
  src/components/ApplicantDetail/component.tsx
  src/components/ApplicantDetail/container.tsx
  src/components/ApplicantDetail/interface.ts
  src/components/ApplicantDetail/styles.module.scss
  src/components/CapabilitiesDetail/component.tsx
  src/components/CapabilitiesDetail/interface.tsx
  src/components/Card/styles.module.scss
  src/components/CompanyLogo/component.tsx
  src/components/CompanyLogo/interface.tsx
  src/components/CompanyLogo/styles.module.scss
  src/components/Headline/component.tsx
  src/components/Headline/styles.module.scss
  src/components/OfferCareers/container.tsx
  src/components/OfferDetail/component.tsx
  src/components/OfferDetail/styles.module.scss
  src/components/OfferInfo/component.tsx
  src/components/OfferSalary/container.tsx
  src/components/OfferWorkload/component.tsx
  src/components/OfferWorkload/container.tsx
  src/components/SectionDetail/component.tsx
  src/components/Tag/component.tsx
  src/components/TagSet/component.tsx
  src/graphql/queries/getAdminTasks.graphql
  src/models/a.graphql
  src/pages/Admin/Home/Dashboard/TaskDetail/JobApplication/DetailContent/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/JobApplication/DetailContent/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/JobApplication/DetailContent/index.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/JobApplication/DetailContent/interfaces.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/JobApplication/DetailContent/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskDetail/component.tsx
  src/styles/mixins/_customMedia.scss
  src/styles/mixins/_customSmallMedia.scss
Labels: feature

#235 Feature/266 job appliation detail info
  src/graphql/mutations/index.ts
  src/graphql/mutations/updateJobApplicationApprovalStatus.graphql
  src/graphql/queries/getJobApplicationByUuid.graphql
  src/graphql/queries/index.ts
  src/interfaces/JobApplication/index.ts
  src/models/handleError.ts
  src/models/hooks/mutations/useUpdateAdminTaskStatus.ts
  src/models/hooks/queries/index.ts
  src/models/hooks/queries/useJobApplicationByUuid.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/Applicant/ApplicantDetailInfo/UserDetails/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Applicant/ApplicantDetailInfo/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Company/CompanyDetailInfo/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/JobApplication/DetailInfo/MainTitle/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/JobApplication/DetailInfo/MainTitle/index.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/JobApplication/DetailInfo/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/JobApplication/DetailInfo/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/JobApplication/DetailInfo/index.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/Offer/OfferDeatilInfo/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/component.tsx
Labels: feature

#240 Feature/266 job appliation applicant reject button
  src/components/ApplicantDetail/component.tsx
  src/components/Button/index.tsx
  src/components/Button/interface.ts
  src/components/ErrorPage/index.tsx
  src/components/FormConfirmDialog/index.tsx
  src/components/SubmitButton/index.tsx
  src/models/hooks/snackbar/useShowError.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/ApproveButton/index.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/PendingButton/index.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/RejectButton/index.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/StatusButton/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/StatusButton/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/StatusButton/index.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/StatusButton/interfaces.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/StatusButton/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/index.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/interaces.ts
  src/pages/Admin/Home/Dashboard/TaskDetail/Actions/styles.module.scss
  src/pages/Admin/Home/Dashboard/TaskDetail/JobApplication/DetailContent/component.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/JobApplication/DetailContent/container.tsx
  src/pages/Admin/Home/Dashboard/TaskDetail/JobApplication/DetailContent/interfaces.ts
  src/pages/Applicant/OfferDetail/component.tsx
  src/pages/Applicant/Profile/component.tsx
  src/pages/Company/OfferDetail/container.tsx
  src/pages/Company/Profile/component.tsx
Labels: feature
